### ISSUE TITLE
postgres_1:  ERROR:  duplicate key value violates unique constraint "calendar_pkey"

### ISSUE THREAD

**Issue by 1ce** [chainpoint/chainpoint-node#1]
make logs:
...
postgres_1         | 2017-09-16T16:17:54.399160244Z ERROR:  duplicate key value violates unique constraint "calendar_pkey"
postgres_1         | 2017-09-16T16:17:54.399565127Z DETAIL:  Key (id)=(6139) already exists.
postgres_1         | 2017-09-16T16:17:54.399796831Z STATEMENT:  INSERT INTO "calendar" ("id","time","version","stack_id","type","data_id","data_val","prev_hash","hash","sig") VALUES (6139,1505578322,1,'https://b.chainpoint.org','cal','6139','a2eae55a6380150c47441342b95a8beaddd95899b17ada557c4073e70108d00b','9fcf65742e23ae1d2c7b7e4cf83135841fd8bb1eb72c1feedd0c9cc5022dc2d5','b2d384213db7fe92aecce7ed688f6a5227af2dd8f95537ff304244585ac12eb5','fcbc2ba6c808:D66ea42LRR/GjpI51RZFd3M8bnpx0kyBLHpLNuTPPG72nztoZxk62CXhi7V8CupV/50chgVZbNktKLZBweFKAg=='),(6140,1505578324,1,'https://a.chainpoint.org','cal','6140','ebce532e837579a2f082418e5eaa22066ae134ba6cfa5bf7823dde512b2e93c4','b2d384213db7fe92aecce7ed688f6a5227af2dd8f95537ff304244585ac12eb5','db5d37d1343a1341ff672340726a5f16949671dcb0e5a1892ed3024a67cbac58','fcbc2ba6c808:Kb30Og8dZYWQHnpDapHFQ2dkzsT9/cGHpPp0iQAga5H15m+57rqntmS95V/FCbfDy5mpZWxXRdtr7ylaM/JRBA=='),(6141,1505578332,1,'https://b.chainpoint.org','cal','6141','91db670fa425850905e2edbd21fd3480e052fda5f3ec89925cfaee4918b5704d','db5d37d1343a1341ff672340726a5f16949671dcb0e5a1892ed3024a67cbac58','f7283c11e0a6564278e49bffc8e39130decbdef387412eea5a5b30989c0b9408','fcbc2ba6c808:cV/yymQ/asKc1bdTIHAodTK791z2dKjxenyC0f3pg4ghMoonqKqYEBh9816l3HYGOTseObkAgn30/OmJdbLWAQ=='),(6142,1505578355,1,'https://c.chainpoint.org','cal','6142','254cb763e00e792d349e140aad1ef405a18b34712268a2846e87b86556035933','f7283c11e0a6564278e49bffc8e39130decbdef387412eea5a5b30989c0b9408','383979ad4c88e5013ecb182aed8bdd2e8f6574a26e02a928ef8722e529572258','fcbc2ba6c808:Nwq8xwOhTzXMcKtdTXRQ1iHeNrEizYFXAhjc1pGjcK7aazBHORw7njZf3AcL/wb6zIRpg1HPZZusoxXOUl8yDQ=='),(6143,1505578364,1,'https://a.chainpoint.org','cal','6143','3c669393330a404fa9b0ae4bcf2dba23697b0a1b08008376d40e777ab591d649','383979ad4c88e5013ecb182aed8bdd2e8f6574a26e02a928ef8722e529572258','589c4adf115806ad87348ad1d69898f180cdc3a4753456dbee950761a670838b','fcbc2ba6c808:AvgypBaUESEGtReCvfLKZNAty72Y/t562CLGvQkEIrWO8JD1Vb/O7Bz8AV7z/u7cOTWi6frlXAv0uePjFZCZBw=='),(6144,1505578372,1,'https://b.chainpoint.org','cal','6144','189f6ca1ef49ffa8315b6187d3a2c861a74c4d7a1899b177bcf98810a7421d59','589c4adf115806ad87348ad1d69898f180cdc3a4753456dbee950761a670838b','9cc921df6feefd3b647c38b4fdeae8dd90d19e78e103a4d8716ad0257503af3d','fcbc2ba6c808:TbaRTY0igE283NeYEuz+THcIe2im1V70ZAZpO7B2Ss24WT/sNwZK0fC0PEww8se6eqRL4OmsQ6r8QPxSKuMLDA=='),(6145,1505578382,1,'https://b.chainpoint.org','cal','6145','8e556c10f9fdb695ad714c9b92459f83fd26d19bef21738a2b2774f255a4adfd','9cc921df6feefd3b647c38b4fdeae8dd90d19e78e103a4d8716ad0257503af3d','bb20559511a76b872cc6813206ea56c7b234c9729a76ee6b2cee8632dd68229a','fcbc2ba6c808:TSqITHzrLsC0Y7mukWhy595IEkSBxLpeoVcNd7+4mFjaCsxGqOPOnFKNYJ6ZUsLrkfJ3lNZg/pWIrCoKNPvNAA=='),(6146,1505578384,1,'https://a.chainpoint.org','cal','6146','2e3d2e45ad66dbb53c7d02d349f088dba1ee21756ca67b8b5a76aa347c71c4c9','bb20559511a76b872cc6813206ea56c7b234c9729a76ee6b2cee8632dd68229a','a7d69eae5238a4b1bdfb25f80b8bc0e54984f7bf42006b36a3c0564a7467077c','fcbc2ba6c808:BmD40CSq7gCuHiwcsxYOSjRqn/NayuX1iOZHNRyQ3k3MGo7Up2OXro7MxE+Q7g4ybS6wKNzjp1T3FByLYdgdBQ=='),(6147,1505578392,1,'https://b.chainpoint.org','cal','6147','a18523ce6ffc8a476ca4d1aad23217efb00faaa2423e8d074868a7b546a2236a','a7d69eae5238a4b1bdfb25f80b8bc0e54984f7bf42006b36a3c0564a7467077c','77554003a369743161cf88d0fb420a975f8e34ce063ab4a1601c1dfb4b4e56e2','fcbc2ba6c808:3M3h/C17nmTJsPfw4inIHIR7yZFLUVoluplkzOPH2WCzrdB2z5eE5ad+OErEwWINp/8fweN1qRw4riw0irAgBg=='),(6148,1505578415,1,'https://c.chainpoint.org','cal','6148','ed258e553544d5c4326c03a7e047550d59313b0693bda4d1aa0684e280f7be86','77554003a369743161cf88d0fb420a975f8e34ce063ab4a1601c1dfb4b4e56e2','3b5c730d6fd18be064db96c2860a87b30053ccbcd789cc317b32e06160847211','fcbc2ba6c808:L9fFtaP71O0AEU/CL8jput4Bnu8fkfZ6MY0O+JmiE8CGg3tPylJxAe85pEr8Nd/6yWDj0mRWfO9O5qg67GkvCA=='),(6149,1505578424,1,'https://a.chainpoint.org','cal','6149','60c9f84f26a527823919125dc3d93bee298dbbeb0fb63a92ece06ebd6e494beb','3b5c730d6fd18be064db96c2860a87b30053ccbcd789cc317b32e06160847211','e31f7901b15963d92d47a1d73f19570a4c3d7725c95509ae09c11c156379e9ba','fcbc2ba6c808:mhe6YkGNw41AZw2istLzOquahM24WVeyEEf+f7vaYWu/4v8832MRDRe689gRRbB/Ag/xFsGX58rBj9lneKokCg=='),(6150,1505578432,1,'https://b.chainpoint.org','cal','6150','53ecd141abc713efdf08db5e3a34633c455904deaa84b2dcea0433e3570bd876','e31f7901b15963d92d47a1d73f19570a4c3d7725c95509ae09c11c156379e9ba','11a7b943b5f2c2a3300ee3283c35141bf22770e4568db7a60c2f9fc8928d115b','fcbc2ba6c808:sj5VUTpTCs7fUz3zLym+sho/4nxqNhJZ9zOIvWu3UGif1zGRTPGNTd4X/J7Klh8o7AUzNurajIOgURwRS9OvBA=='),(6151,1505578442,1,'https://b.chainpoint.org','cal','6151','bcdfaf16fbe36984721021c37c2d2d01e9f1b8171ddef5e4cc5444133b7983f2','11a7b943b5f2c2a3300ee3283c35141bf22770e4568db7a60c2f9fc8928d115b','263d5937fe4a54437b701afbb5ee091dde196b7c8ff7d2e2b4050a0cf07b3452','fcbc2ba6c808:BYP+wKO/4VVYi5nPolg5mTqS3oAY0FVg3p4AShX2UD3pkpr7YFdWF48UPK+Og08J9VEFjcpvna7PrQaQaUqfCQ=='),(6152,1505578444,1,'https://a.chainpoint.org','cal','6152','4be542ee8c57a19b4dcca12147924e1237be5e92ddd738a3cf03e52d1f9ca2cb','263d5937fe4a54437b701afbb5ee091dde196b7c8ff7d2e2b4050a0cf07b3452','230b666998d70530f3016fb0bc2e82459b69fa6984c5ac814c3164113803a98c','fcbc2ba6c808:F97qTclUIq0r2fVvmtjWaZCW5s0QlKoMwcSGd0OKcdn75KTRrVWhyYybPvHAOP9gwjbRVFJ27KnXKEnIHlSEDw=='),(6153,1505578452,1,'https://b.chainpoint.org','cal','6153','57082e28557e00685eb45f963451783e484e7ed688437005e0c7650e84849652','230b666998d70530f3016fb0bc2e82459b69fa6984c5ac814c3164113803a98c','e1c944775bd0d2168eba05a1d01ba0b66f439e3fdbca7826ba0353ccb102858c','fcbc2ba6c808:8+89G5psByeE4YvIzhmMjNEyRiKOJYTm1sD4J4AWGJ0CHgwYZEFJ8gr/svJGZAIT6vG8VmCM80OD49Vc0/v6CA=='),(6154,1505578475,1,'https://c.chainpoint.org','cal','6154','f2894692ffb63440f68af6ab8a8d8ea1becfcd845735093eec0da56a2f5218c7','e1c944775bd0d2168eba05a1d01ba0b66f439e3fdbca7826ba0353ccb102858c','4ab549979934ce2d1c8cb99213af082b335c401e6305d01cadc3ec7d1ca06c46','fcbc2ba6c808:j3/UMOKhcB0FdZFUz/2gVtXpquLqI3xALoKsP6Wlfd4aPfZSXhEMtmW5N6AGmBSXWZSbUfRKW4xnhnkZ5SOxDw=='),(6155,1505578484,1,'https://a.chainpoint.org','cal','6155','98c0b4a7bc1290d6ca5765eb7d78f2840d9ea1cb26612d4f95896f6a3a97be1d','4ab549979934ce2d1c8cb99213af082b335c401e6305d01cadc3ec7d1ca06c46','e872b0f855885c5cccf53bd1a4cb155c54370f43684f8baa1f5cab99e1d1a053','fcbc2ba6c808:BTOdzZTAv3qRSXrh0gFFW/OBvbr2krGZHGRS+p0Iddvcg97JJdUhxHE67LiYpoRH3OGeyQ8hlb2NVi8VMptJCg=='),(6156,1505578492,1,'https://b.chainpoint.org','cal','6156','16157e2cc61e97637c578736b17b4bccce2f6552f9a24b1ba6b3589b96fdb1e1','e872b0f855885c5cccf53bd1a4cb155c54370f43684f8baa1f5cab99e1d1a053','3ec7ea3b556dc66534648a2cca4dd1dbd2cadc2a2a5745af27de524b5e08799a','fcbc2ba6c808:+h2rAur16rZ1HuSgwSP4VSFjfGUQDCKGJHNUSmeyoHb3QHd2uZp4bMkHQHhKvzgd1gnbPrSmSXs8hDoSq9OsDg=='),(6157,1505578500,1,'https://b.chainpoint.org','nist','1505578440','cc5199695c1108f256e962a82783535d4854f586e414ab00331fb60c279e1d88d7785b1577760f0db754da1157dace76ce06f374664e682af2b34b4e031772e5','3ec7ea3b556dc66534648a2cca4dd1dbd2cadc2a2a5745af27de524b5e08799a','fe8bdd785cde9664475816550d6109c508a0f8f38de60322447529dd92498d8b','fcbc2ba6c808:XbYq6Jef81WDjXQaMd/Fzd8RLcjQNcPr8whsE+MoQS2i9/5YoD0h/xqjAkwx+LRwv/cbILlBkCjOT6MMPFrPBA=='),(6158,1505578502,1,'https://b.chainpoint.org','cal','6158','d06fcc24137f061071008eab3cad8e8e766bbbe508d90a7c12e75ec092a2b8b4','fe8bdd785cde9664475816550d6109c508a0f8f38de60322447529dd92498d8b','f57c396140efaca2fa464f726caf62fb3a4b8576fe1046a3fd14002cb33735ea','fcbc2ba6c808:h4pc8AzMnowZbsRSe9P7OwLso59WuuCXWj5IUzE4YBE81JW9+Iju6pVc3xUOPjZwBKzrGioFhtjLMKLWDEBJCQ=='),(6159,1505578504,1,'https://a.chainpoint.org','cal','6159','92ab7469e2f28ec429e2adbf27b8e2fc1b5755933974076bec97ae01afd61b6f','f57c396140efaca2fa464f726caf62fb3a4b8576fe1046a3fd14002cb33735ea','781a9fa60967b12b4f0df811506153382821a2266b2ce62a6bb526e468d7bb79','fcbc2ba6c808:pd2PoFQTftF849VLkJ1WtWEBwMVmm6vLrnftkH36RHsj67Guu9d+2HWUN3u0RnEmKRwnrE6AjkhgSOMol6DZBQ=='),(6160,1505578512,1,'https://b.chainpoint.org','cal','6160','74c573fdfd7c06ea962b7148569afdb834e4926dcf2f03569ce3b875dcc3f505','781a9fa60967b12b4f0df811506153382821a2266b2ce62a6bb526e468d7bb79','0a20e381adfba43b5a4e9cc531d9ae70e8626eaf2f940ff392a065495a344d7d','fcbc2ba6c808:m2TYZpeybu5acXxYsel4tdeIBArCnqY+BomdfpeCv12NKWtYDRAbKHiT7dvojhFQtxHBzs1puc66psaq16SMCQ=='),(6161,1505578535,1,'https://c.chainpoint.org','cal','6161','aee9dea535eed0244ec7105e18285eccdbc8243a7c76f06ac481e7dcc2297003','0a20e381adfba43b5a4e9cc531d9ae70e8626eaf2f940ff392a065495a344d7d','1e27309e15917abb9c014fe5243a163a04785e49dbb12910f5ea7576fc1eccb7','fcbc2ba6c808:bRvagC5KDz2xcXL22uax5W3PY9GX3g+ZF4U+lGFq7Bxxx9pS4PRTCsVEUScg3in0Mo+j7DuSTGJ4BCoE/wLKCA=='),(6162,1505578544,1,'https://a.chainpoint.org','cal','6162','154b2aae180ab6c459d7a4e6c45a200a2a934f26cd7248caf4b6ac3983bbe913','1e27309e15917abb9c014fe5243a163a04785e49dbb12910f5ea7576fc1eccb7','13726dc6620f3f9730dc19dd376466c15d20be1cd07486df64caca6edc177866','fcbc2ba6c808:Zsiv7SrIzhC4UHNeevm7xxCw2niQU0u9wze2M/ELxVdKppEQ5KBqDNlRW/xxXRP0pVqPjoyvb+kRjv4+a58BDg=='),(6163,1505578552,1,'https://b.chainpoint.org','cal','6163','8d51681f4bfdcfbfea3587ee9d22ff2fb03d9e4f425af058c3c22bdca20ac678','13726dc6620f3f9730dc19dd376466c15d20be1cd07486df64caca6edc177866','1d20aa01ea59cd2eaa2d1cc51d6c17329617d6f70a6c154b0c66a7fc255b07f1','fcbc2ba6c808:kIkVOjz/CM6lUfJeB54K/6n+INWO66Rj9W2FkalMNPelzYYKoe1+8qzqZ8LNpjowyaVObkgMnaij5HQxOOVDAA=='),(6164,1505578562,1,'https://b.chainpoint.org','cal','6164','c6cef3fdc27d827987305aa6a6da2090da04eb3fcd8122fc4799cfade53ebe1e','1d20aa01ea59cd2eaa2d1cc51d6c17329617d6f70a6c154b0c66a7fc255b07f1','87023689300df36a54792eee0e2b802de109d60fe4035b6a8448fc6b264726e9','fcbc2ba6c808:FDitX3QGgzeYspAyOL/Vib1hnCX8zxsaVW6ElQPFoCQSiq8jRQ7ZKszhD4yPRTRhoDnj3HhlHjSpE8LKcDLdBA=='),(6165,1505578564,1,'https://a.chainpoint.org','cal','6165','cc875406dc860312b459009a472ff1ca39e5e7def573d54b210b9264d643329b','87023689300df36a54792eee0e2b802de109d60fe4035b6a8448fc6b264726e9','6b53bab2fabd07bf4521bdb645de7e6caee2ae94c979a76514bc966897375ee4','fcbc2ba6c808:k5Zx9iJHFoy5burQK0zC4BxFsVS1+YgA5/ApsXBHSJPIy3rQqDjGqbcCWgmv55s4TM8lA32w99zF12A85zrfAA=='),(6166,1505578572,1,'https://b.chainpoint.org','cal','6166','14b943183ade2db61502403ea79f40a093c734231e01aa63019517a363bbd088','6b53bab2fabd07bf4521bdb645de7e6caee2ae94c979a76514bc966897375ee4','243c7eeee06eea452d155d7923f96b562bac6f2dbf9b2203dc44e2f36638965b','fcbc2ba6c808:5gzgr9dIZE4I79wbvefXqBaNgelN/ZCHyPKUtrvIyGE1YWHx7Uw3s1c6x9WDDxB93EJsD41j7y+8VTyv4mD6AA=='),(6167,1505578595,1,'https://c.chainpoint.org','cal','6167','b48f361d2b39690a4330b8e7869a9e4873e9c02c178ce943eef0ea95d6fb4359','243c7eeee06eea452d155d7923f96b562bac6f2dbf9b2203dc44e2f36638965b','a1234ccba14ce2eea55c59475e154f54c197d1c710308668dbcf4062a7cab341','fcbc2ba6c808:w3dqP7tVfWa65FanYt77hKu8Rh0IDzuaa5ZRNzyPV8fQWwYMcGkHrV8Ybro2BhJjJHG5kTybeFFAmyy3cC+DAw=='),(6168,1505578604,1,'https://a.chainpoint.org','cal','6168','46a334af7584da98920e039b6a479eeb3ecebbbd2c939900cdbf388dd1fa2422','a1234ccba14ce2eea55c59475e154f54c197d1c710308668dbcf4062a7cab341','8b74a725f952f458d335af91cda02de49f1d7bbfd6e982427e2d1744e32626eb','fcbc2ba6c808:YDxmV37jI+vzEYiuSvhDTqsGzihs2cXpQw67279A5EmzfKv/8F+AgRa6S33ECPIi+7MYIG+cqDd6bEcRZIa9Aw=='),(6169,1505578612,1,'https://b.chainpoint.org','cal','6169','61f2ed2aac414e9eb66bbf4fb0a87531b408139fb60f16fe368d7234cc02e316','8b74a725f952f458d335af91cda02de49f1d7bbfd6e982427e2d1744e32626eb','d5de23e75b989a7517aa366d5510d23eb290a07685a3d43ecf175fd91466b7e6','fcbc2ba6c808:obhExBO2ZdxxzjQsf7Vi1o9MrBb3wyWNcGRw/inpnNNOAqGzV+mAq0ch4zIZgiG4LX0lxl+/G5u9Snf6qr3vAg=='),(6170,1505578622,1,'https://b.chainpoint.org','cal','6170','65176c5a82a2518cf0eaa257f20d6a6cd191f779840b38fd707dc68a5b146817','d5de23e75b989a7517aa366d5510d23eb290a07685a3d43ecf175fd91466b7e6','6fd37873299298b0e1b1aeae086e04fffe64af9a07be9ed2e69bb0c23f5b8d0e','fcbc2ba6c808:HxRdlKNYLq4RSyDCv59cwQH47oEtzNsICO7MORkVRxf5Glcp7J5skwOqG1npUMNyGkMXoF3j3ztGCYabX8mgBA=='),(6171,1505578624,1,'https://a.chainpoint.org','cal','6171','fedffe665d0fca68ab28f700d0923868c38e6ef60322b60dd8b716adb41e2f1d','6fd37873299298b0e1b1aeae086e04fffe64af9a07be9ed2e69bb0c23f5b8d0e','fbf8f077fb055f2ad1a3b69e896b9744031f4487e0a224f79528bee2090a99b5','fcbc2ba6c808:0E8BI1gNYSLmCcxwCG7GyFQJ2CsV/l15L4L/wN+6tOgnYgO2fcrTC3ANVFLpFnGXhRCvoodx5aO0dPqE+xplBg=='),(6172,1505578632,1,'https://b.chainpoint.org','cal','6172','3787027f7158500ed1f80b3b49cd881107cee8ef345ebea5ee070ea0daf70e0a','fbf8f077fb055f2ad1a3b69e896b9744031f4487e0a224f79528bee2090a99b5','d5cbd42e5fc44c350fa0635481c5be92077a05568b2fc1b8b6d227affb0bd056','fcbc2ba6c808:Ux1ifRLhE0CFsAOxmYp+RFXIAlHSVT13xRFGjRKIRg1WQgKpyWoFZmHry2Q6v4JET6QJTD9vTFdXuMk3YzLTBQ=='),(6173,1505578655,1,'https://c.chainpoint.org','cal','6173','510e3e5d50f38411c8ae0e4bee6f9b9728359faf252d427b59ae0f1577b3fd69','d5cbd42e5fc44c350fa0635481c5be92077a05568b2fc1b8b6d227affb0bd056','b858e13afed5b7648eaa4d1d85f43b97f33dab6da363f19b9fbab5aa4c5d8505','fcbc2ba6c808:oId7dN1OaWKI4Ngv0bS0TzuC+XG/fw0oYeLZVkyYgI7nV0GEDgT2Q51b0ZuDtEiOZZhjgL3ZPYcxahp5iTCHCQ=='),(6174,1505578664,1,'https://a.chainpoint.org','cal','6174','9fec6430e629d0b903f04b9269d288a52c25edbedc18c862f186cb85cee4707a','b858e13afed5b7648eaa4d1d85f43b97f33dab6da363f19b9fbab5aa4c5d8505','88f47fac59f6750ed262d399ddc09dda1c218025b9439d2a2658e180fdc3270c','fcbc2ba6c808:r5NTjzZOqWx6LsJinGCfe7kTL5yq23QZhTNdk54D0cKUNi2qe0J9c+xe3oOGu+gW2oIfedNBa0GtzjFF6fUAAA=='),(6175,1505578672,1,'https://b.chainpoint.org','cal','6175','c0231a06e891a7256d9e1f17b6e6118d3e014d830b7b7e130a5e7fe3bceeaa3b','88f47fac59f6750ed262d399ddc09dda1c218025b9439d2a2658e180fdc3270c','392ac3e4b47eae0d375fbeb7ef274ea2d8cf207652c1e67021b0f287d9d078eb','fcbc2ba6c808:rKDYFLoI7j8SKHD/FEWkFhMDNb6kD5bhGEp7g+dlCokqZFWkRxQW2ttnoL6IKbXD1dBsaDGHcc3NimLalcUQDA==');
chainpoint-node_1  | 2017-09-16T16:17:54.407884210Z Error performing calendar update : Validation error
...

**Comment by adamluc** [comment]
I also got the same error

**Comment by grempe** [comment]
This should be able to be safely ignored. What seems to be happening is that your Node is retrieving calendar entries from Core and trying to insert them into your local postgres DB instance on your Node. However your Node has already retrieved those Calendar blocks previously and the duplicate primary key can't be inserted. Check your audit results as shown in the FAQ on the Wiki, and your calendar state audit should be true.
