### ISSUE TITLE
The credit number is not updated.

### ISSUE THREAD

**Issue by HyeonghunLee** [chainpoint/chainpoint-node#10]
I sent 100tnt for making credits, setup nodes normally at many times ago, 
https://a.chainpoint.org/nodes/0xE7f31C38a0D47C03127714FD14e2373DEaeB061f

and its correctly sended already:  
https://etherscan.io/tx/0x24e5009bd02cf0459f1943e88b44aa0126ea3b864f8dc15db47afc93fd7cd47a

But in a.chainpoint.org(b,c whatever), displayed as:
credits: "0"
minimum_credits_test: "false"
And all other list are displayed as "true".

I set up another 4 nodes, tnt sended for creating to credit, without any other problems. 
I put same tnt tokens(100) to the core address through the specific node eth addresses. 
Each eth address is held at more than 2500 tnt. 

I have also tried node update(git pull command), but they are all the same symptoms. 

I do not know what else to solve this problem..

_(add more problem) Block height stuck issue_    ---this issue has been solved
-------------------------------------------------------------
_After upgrading the node (using make down -> git pull -> make up
 // source: https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions)

Block height stopped at 15234. (displayed both "http://[ip4_address]/config" and "logs file")
What's wrong with this?_

**Comment by grempe** [comment]
This issue should be resolved in the latest version of the Node software. Please upgrade as described in the FAQ page of the Wiki in this repo.

We have temporarily disabled the need to submit TNT for credits and your account has been topped up with the maximum credits needed to operate a Node on a daily basis. Please see the update in the README for more info.

**Comment by HyeonghunLee** [comment]
@grempe I know that you are struggling to solve problems after the software launch.
 I am very impressed with the efforts of you and dev team.
Unlike other ico, there are very few tokens already launched to the main net, and I have very high expectations for TNT.
As I operate my nodes, I will keep watching the development of TNT.
