### ISSUE TITLE
UPGRADE ERROR: readlink /var/lib/docker/overlay2: invalid argument

### ISSUE THREAD

**Issue by Arsca** [chainpoint/chainpoint-node#100]
Hi,

1. Run 'make upgrade'
...
`#################################################
Start ntpd service container if needed
#################################################
make[1]: Entering directory '/root/chainpoint-node'
Local time sync daemon seems to be running. Skipping chainpoint-ntpd...
make[1]: Leaving directory '/root/chainpoint-node'
#################################################
Start upgraded Node
#################################################
Creating network "chainpoint-node_chainpoint-node" with driver "bridge"
ERROR: readlink /var/lib/docker/overlay2: invalid argument
Makefile:84: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1
root@cf1:~/chainpoint-node#`

**Operating System :
 - OS: Ubuntu 16.04.4 LTS
 - Output of `uname --all`
Linux cf1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Browser (for Node UI):**
- Browser Type Chrome

I would like to know how to pass this error or if required  installing it from scratch what would be the steps?

Regards,

**Comment by michael-iglesias** [comment]
@Arsca 

Try running the following and report back to us whether or not that corrected the issue:

1. `$ docker-compose down --remove-orphans`
2. `$ git fetch && git checkout master && git pull`
3. `$ make upgrade`

**Comment by Arsca** [comment]
@michael-iglesias 

> Upgrading to 1.5.4 will require the following upgrade command:

I read the blog and did it accordingly withe the same command.


This is the result of the commands : 


>  root@cf1:~/chainpoint-node#
> 
>  uname --all
> Linux cf1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> root@cf1:~/chainpoint-node# docker-compose down --remove-orphans
> Removing network chainpoint-node_chainpoint-node
> root@cf1:~/chainpoint-node# git fetch && git checkout master && git pull
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> Already up-to-date.
> root@cf1:~/chainpoint-node# make upgrade
> curl -sSL https://chainpoint-node.storage.googleapis.com/upgrade.sh | bash
> ...
`
Creating network "chainpoint-node_chainpoint-node" with driver "bridge"
ERROR: readlink /var/lib/docker/overlay2: invalid argument
Makefile:84: recipe for target 'upgrade' failed
make: *** [upgrade] Error 1
`

**Comment by Arsca** [comment]
This is the installed docker version:
root@cf1:~/chainpoint-node# docker-compose -v
docker-compose version 1.21.0, build 5920eb0
root@cf1:~/chainpoint-node# docker -v
Docker version 18.06.1-ce, build e68fc7a

**Comment by michael-iglesias** [comment]
@Arsca 

Can you run `$ docker ps` and provide the output?

**Comment by Arsca** [comment]
> root@cf1:/tmp# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by michael-iglesias** [comment]
@Arsca  

Try running:
1. `$ docker network prune`
2. `$ docker system prune -a`
3. `$ curl -sSL https://chainpoint-node.storage.googleapis.com/upgrade.sh | bash`

Let me know if that resolves the issue. If that doesn't work I have a few other ideas that we can try based on some of the research I've done regarding this issue.

**Comment by Arsca** [comment]
@michael-iglesias 

Thanks!  That was it, it's up and running :-D

**Comment by michael-iglesias** [comment]
Awesome! Glad we were able to figure it out.

Happy Holidays!

**Comment by Arsca** [comment]
Closing this as resolved.
