### ISSUE TITLE
[Question] Private Calendar Blockchain

### ISSUE THREAD

**Issue by mcanzerini** [chainpoint/chainpoint-node#101]
Hi Chainpoint crew,
Is there a way to run a private Calendar blockchain on premise by running some Chainpoint nodes on our servers and anchor the merkle root in a public Blockchain ?
Or do we have to fork the code ?
Thanks !

**Comment by miketwenty1** [comment]
You currently can run a private chainpoint node and that will send merkle roots to chainpoint core for timestamping against the chainpoint calendar and the Bitcoin blockchain.  The chainpoint calendar is utilized for the entire chainpoint network without leaking info or data to other participants.  

May I ask why you would want to run your own "chainpoint calendar blockchain" instance?

**Comment by mcanzerini** [comment]
Hi. Thank you :) 
Me need is : run my own (private) chainpoint core (with multiple chainpoint node) on premise on our servers. Without connecting to the public chainpoint core.
Is that possible ? 

I want to run my own chainpoint core because we want to be sure that the core will never stop running

**Comment by miketwenty1** [comment]
@mcanzerini We don't have documentation on how-to easily run chainpoint core.
We are currently in the process of making core more decentralized and easier to run. Stayed tuned to our social media / telegram / twitter / discord / github. 
We are trying to make the most robust time-stamping service and hope you will want to be part of the main chainpoint public network. This includes individuals and groups having the opportunity to help run chainpoint core.

**Comment by miketwenty1** [comment]
As I mentioned we are in the process of changing up core, but yes currently all of our core software is open source:
https://github.com/chainpoint/chainpoint-services/blob/develop/README.md
