### ISSUE TITLE
[Question] How could you prove a proof without using the cli or verify endpoint

### ISSUE THREAD

**Issue by Yamto** [chainpoint/chainpoint-node#104]
Hi,
I'm wondering how you would prove proof without using the CLI or verify endpoint.

So someone manually could run through the proof and create the Merkle hashes logged on the various blockchains(cal and bitcoin).

Thanks in advance

**Comment by jacohend** [comment]
Hi Yamto, please see this tutorial: https://runkit.com/tierion/verify-a-chainpoint-proof-directly-using-bitcoin using chainpoint-parse@3.3.1.
