### ISSUE TITLE
What is the ERROR ?

### ISSUE THREAD

**Issue by tori365** [chainpoint/chainpoint-node#11]
{"code":"MethodNotAllowedError","message":"GET is not allowed"}

**Comment by grempe** [comment]
Please provide more context. The full logs around where you saw this.

**Comment by tori365** [comment]
I was [make down]　→ [git pull] → [make up] in my node.
An error has appeared from that time

**Comment by grempe** [comment]
This appears to be the result of your trying to access the now removed `/nodes/0x...` endpoint for checking credit balances. It was removed over security concerns. There is an alternate in the FAQ.

https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions

If you feel this is closed in error, please provide details (copy or screenshot of relevent logs)
