### ISSUE TITLE
Did not receive any reward yet. Why?

### ISSUE THREAD

**Issue by muntasirjoarder** [chainpoint/chainpoint-node#15]
Hi, 

I installed the node following the Github documentation. It is running from yesterday. I checked the following URL:

https://etherscan.io/address/0xEabCF7171c7c4ea66bd3a03a1E9459057506Ed5D#tokentxns

and found no reward was transferred. 

I also transferred 80TNT to the public etherium address that you suggested for credit. Please check txHash: 0x96dde31102c2b6789e5b9c81ea3884e51b1d96acb4ac271a40f69b05f76a4292

Please suggest what should I expect. And if there is anything that I am missing.

**Comment by grempe** [comment]
Rewards are not guaranteed. Your Node must be chosen randomly from all Nodes that pass all audit tests.

I see that you have 11830 credits in the Database at this time.
