### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by Richardxlin** [chainpoint/chainpoint-node#17]
Context: Brand new install. Key generated and blocks synced.

postgres_1         | 2017-09-18T03:05:29.645283224Z ERROR:  duplicate key value violates unique constraint "calendar_pkey"
postgres_1         | 2017-09-18T03:05:29.645377375Z DETAIL:  Key (id)=(21403) already exists.
postgres_1         | 2017-09-18T03:05:29.645465208Z STATEMENT:  INSERT INTO "calendar" ("id","time","version","stack_id","type","data_id","data_val","prev_hash","hash","sig") VALUES (21403,1505703840,1,'https://b.chainpoint.org','cal','21403','b33a6f690a27c81837da7de2061fd03773d47e4a72eaa8bc2371dc987ac385e7','aeb05b76397f97e6414e454b31b25e7bb8f04b1b98a6ca2f3d51d01b6d6799f8','54b887e97870acf42200846fd6f91019fc90de5f41495ebd5194b27c8e9be7bf','fcbc2ba6c808:ElJLd/QdlQNKss3AZ6rjEepc0+0O4zWcp1Duzm3WWhChtj9IP3iyq0WXSQ3tmmyrYXXSe2rsDGIFQ77AJ5XmDQ=='),(21404,1505703842,1,'https://c.chainpoint.org','cal','21404','8ac793dfd835961633e420aca2cec7aee8a31e4ad6c9510479ae839f98ae131f','54b887e97870acf42200846fd6f91019fc90de5f41495ebd5194b27c8e9be7bf','2ff67269ee12f55c6e1e49f4b4a1498468f152a08053c5f2518b504f59dd916d','fcbc2ba6c808:AiEnTxMhFSrgRY63kDdYgDZFduteOe3qNAGjabfQHTSPVPAp5UR7UnSfOjFvI7WkZJ4Uj0hghEGsVNUB4dN2CA=='),(21405,1505703855,1,'https://a.chainpoint.org','cal','21405','20ef7b1956d7e349af806ae581b69ceaf618f8c70b108a551fb06dd2799e85ef','2ff67269ee12f55c6e1e49f4b4a1498468f152a08053c5f2518b504f59dd916d','806a7e7f2f65daf812068e93b1371527bef2a612aa587aea885c2df3f2bdba23','fcbc2ba6c808:2Omsg5uBOLC0+/FvcaQxvFg52niOa5GNlWrKIVKxEbFmko4mEmfAvsH+SPdl1S2bcWcPJd5JZ/JAwbk86ZIoCA=='),(21406,1505703875,1,'https://a.chainpoint.org','cal','21406','cf12870def8dd4239bb99d245b144896bfb9690c20b7fc0320ad88267af44d01','806a7e7f2f65daf812068e93b1371527bef2a612aa587aea885c2df3f2bdba23','39426c95c4d0733fb82fc47b1eae742b943822951f0867ae5b9991d552d877ee','fcbc2ba6c808:cbtIbAPORmkvkUg69byRi/cw8cGOUVvGtpO19bQW45GfXFTcgM7ZIdWhfUiYe7lP7K01rdjjWAbsr7jZNg2iBQ=='),(21407,1505703885,1,'https://a.chainpoint.org','cal','21407','1129152cf62476619d8a6da4200b6184901dfd54befd5da63db12dc5f021d453','39426c95c4d0733fb82fc47b1eae742b943822951f0867ae5b9991d552d877ee','7589cf3eae64a6da84371c79c23b1fd98b291d70f96f68662c92b3798ba782ff','fcbc2ba6c808:jqqZAo9/SfY1uEayj1rsDId8VcRsOYz5vOo9s8Pj+XA1tALmNvQxkqDMBXfFAkLfRiW01jAHqU/UxkUxHzx0Cw=='),(21408,1505703892,1,'https://c.chainpoint.org','cal','21408','96b1f1d117397a997dfc4b96e0fe60dc949179d039cffeb619eca57298219c0a','7589cf3eae64a6da84371c79c23b1fd98b291d70f96f68662c92b3798ba782ff','e5f00a388f09ff83bf5baab3b35d9233950a044fe6f50c1cf07b9c7a4b45050b','fcbc2ba6c808:Oi4neoU1ShrTDPt3tLyuCUOCftJ37iANSgAwY+DAVIkQy1k4pSwbHKhTrmZSu1nZB04ng3h57XrDlkhbq0lHCQ=='),(21409,1505703902,1,'https://c.chainpoint.org','cal','21409','843fda47528a478b30a4d72be9dcc6b23f414c4a5f209ce35efa4a65e04bb98f','e5f00a388f09ff83bf5baab3b35d9233950a044fe6f50c1cf07b9c7a4b45050b','deba8fd83105f374cc12cccbb9fbba266c8cfb874dd1140c97eae2f41328f788','fcbc2ba6c808:f+klBqn+cKrW8z2DabnO0WOjRqOTtfnp22elRi3LeJByOSIJNb+b+iWLUFs34mJx8oQPJ3P9Y85YobhgRfkwAQ=='),(21410,1505703915,1,'https://a.chainpoint.org','cal','21410','195c437996496c728d804ff469e967347df34c9f47bc23a288e249ea68317be4','deba8fd83105f374cc12cccbb9fbba266c8cfb874dd1140c97eae2f41328f788','dc857fcfa11b40f1578cb3ca03bcfb6b680c82ba1cc5551d1f59ce95015fffa5','fcbc2ba6c808:2CGPuQqXK4XYNMgqoQFGqp0kGKvVAhqeJaScrE0HwgNLBxq6AgIpEU8KZ8DTPTp28F8tIKsjINk2XnruxrCNDQ==');
chainpoint-node_1  | 2017-09-18T03:05:29.654958260Z Error performing calendar update : Validation error

**Comment by grempe** [comment]
This issue has been resolved in the latest version of the Node software. Please upgrade as described in the FAQ.
