### ISSUE TITLE
Network Credit Consumption

### ISSUE THREAD

**Issue by accrubit** [chainpoint/chainpoint-node#19]

**Comment by VVILD** [comment]
also in this ddos attack it is impossible to still keep your node running as i keep getting cloudflare warning on submitting hash to core .

**Comment by xuwenjie14** [comment]
Getting cloudflare error, and impossible to keep node running. Burning credit fast,

**Comment by grempe** [comment]
This is an issue that we are investigating internally, and we will provide updates as appropriate. There is a significant amount of misinformation in this post.
