### ISSUE TITLE
Credits sent before "make up"

### ISSUE THREAD

**Issue by sadgb** [chainpoint/chainpoint-node#20]
While writing my script i made a huuge mistake and buy credits before i run the node for the first time. 
Sadly 90 nodes spent 100 credits each, total: 9000 TNT. 

As I guess that should be easy for you to re-run parsing  of transactions to you smart contract now, when HMAC is already generated for my addresses. 
I think so because the part which is working with credits is outside of blockchain. I understand that you couldn't revert TNT-to-credits transaction cause it is in blockchain already. But re-run your script giving coins for failed transactions should be possible. 

I am not the only one with this issue. Please help me, because i was making nodes for my friend and lost some of his money

**Comment by grempe** [comment]
We have temporarily suspended the need to submit TNT for credits. Your account has been topped up with the maximum credits needed to operate every day.

Your original TNT submitted will be accounted for in an update to the credit model that we will announce in the near future.
