### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by Graceas** [chainpoint/chainpoint-node#21]
I have gotten the below error:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): TypeError: Cannot read property 'proof_data' of undefined

and

Error querying for proofs on Core : Invalid response : 521 : 521 ...cloudflare error page...
Error querying for proofs on Core : Invalid response : 520 : 520 ...cloudflare error page...

**Comment by Graceas** [comment]
One more error (credit balance > 80k):
Could not submit hash to Core: Invalid response : 401 : 401 - {"code":"InvalidCredentials","message":"authorization denied: ResourceRequest timed out"}

**Comment by grempe** [comment]
This should be resolved with updates we have made to Core as well as upgrades to the Node software. Please update to the latest release as described in the FAQ page of the Wiki in this repo.
