### ISSUE TITLE
Validation and Proof on Core error 

### ISSUE THREAD

**Issue by muntasirjoarder** [chainpoint/chainpoint-node#22]
chainpoint-node_1  | 2017-09-18T12:14:53.897091572Z Error performing calendar update : Validation error
chainpoint-node_1  | 2017-09-18T12:14:54.106200621Z Error querying for proofs on Core : Invalid response : 521 : 521 -

**Comment by 1ce** [comment]
I also got the same error on all nodes

**Comment by grempe** [comment]
This problem should be resolved by upgrading to the latest version of the Node software, as described in the FAQ page of the Wiki of this repo.
