### ISSUE TITLE
I changed my node global IP address. After that, there are no logs about "Hash submitted".

### ISSUE THREAD

**Issue by shinji2000** [chainpoint/chainpoint-node#23]
I changed my node global IP address, because of add memory to my VM.
After that I changed .env file then "make up".

I can't see logs like " Hash submitted to Core: hash_id_core: ... remaining credits: 1
1986".
Before change global IP address, my chainpoint-node work well

I check this below command.
~/chainpoint-node$ docker-compose logs | grep hash_id_core

I would like to know how fix this issue.

**Comment by takeratta** [comment]
+1

**Comment by grempe** [comment]
This is not a bug. It just means that there are not currently any hashes being submitted to your Node as your Node has not been discovered by any clients.
