### ISSUE TITLE
Cannot submit hash to node via chainpoint CLI

### ISSUE THREAD

**Issue by cgrohowski** [chainpoint/chainpoint-node#25]
When attempting to submit a hash to my node (to check my credits) i get the following response:

"<Hash submitted> | ENOENT: no such file or directory, open '/home/<my user>/.chainpoint/chainpoint-proofs.db' "

I am using the latest node pulled from git Sep 18.

**Comment by hydrarulz** [comment]
In your local home directory you should have the `.chainpoint` folder created.
It seems your `$HOME` variable is not correctly set

**Comment by cgrohowski** [comment]
My apologies, it seems this folder was created as root rather than the user so it was a permissions issue.  Marking the issue closed.
