### ISSUE TITLE
how to check my credits?

### ISSUE THREAD

**Issue by jeff798** [chainpoint/chainpoint-node#29]
how to check my credits?
I am not sure whether my node is qualified.
my address is 0xEca93b4d410B3B81637203203a6243868bD98a12

**Comment by sgarciafer** [comment]
there is no way at the moment to check the credits except if you send a hash to your own node. That will consume 1 credit and the total amount of credits will show on the logs.

**Comment by grempe** [comment]
You can see the credits available to you in the Node logs when a hash is submitted to your Node.

Since we are temporarily topping up all accounts with maximum credits per day all accounts will meet the minimum requirements for credits on each audit check.
