### ISSUE TITLE
There is an issue between Cloudflare's cache and your origin web server

### ISSUE THREAD

**Issue by huanghao2008** [chainpoint/chainpoint-node#3]
<p data-translate=\"try_again_in_a_few\">Please try again in a few minutes.</p>\n\n      <h5 data-translate=\"if_website_owner\">If you are the owner of this website:</h5>\n      <p><span data-translate=\"520_owner_desc\">There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href=\"https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520\" data-translate=\"addtl_troubleshooting\">Additional troubleshooting resources</a>.</p>\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>39fb24b83db47930</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 104.225.153.44</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div>\n\n\n    </div>\n</div>\n"

**Comment by grempe** [comment]
This was caused by a temporary server side issue which should now be resolved. Thanks for the report.
