### ISSUE TITLE
Ethereum (TNT) address and url is invalid

### ISSUE THREAD

**Issue by ken0509** [chainpoint/chainpoint-node#32]
it seemed to go well at first, but now invalid as below.
another node is still fine. how can i fix this problem?

chainpoint-node_1  | 2017-09-19T14:23:21.949969430Z yarn start v0.24.6
chainpoint-node_1  | 2017-09-19T14:23:22.092850269Z $ node server.js
chainpoint-node_1  | 2017-09-19T14:23:22.203079717Z ============================

====
chainpoint-node_1  | 2017-09-19T14:23:22.203140032Z  Invalid environment variabl

es:
chainpoint-node_1  | 2017-09-19T14:23:22.203144769Z     CHAINPOINT_NODE_PUBLIC_U

RI: Invalid url: ""
chainpoint-node_1  | 2017-09-19T14:23:22.203148054Z     NODE_TNT_ADDRESS: The Et

hereum (TNT) address is invalid
chainpoint-node_1  | 2017-09-19T14:23:22.203150928Z
chainpoint-node_1  | 2017-09-19T14:23:22.203153401Z  Exiting with error code 1
chainpoint-node_1  | 2017-09-19T14:23:22.203155921Z ============================

====
chainpoint-node_1  | 2017-09-19T14:23:22.207777136Z error Command failed with ex

it code 1.

**Comment by sgarciafer** [comment]
You need to set an URL on the .env file my friend.

**Comment by ken0509** [comment]
thank you so much! i set again and my concerned error has fixed,
but there are still some errors...i hope those error are not caused by myself.
