### ISSUE TITLE
How to make renewal my node for trouble shooting

### ISSUE THREAD

**Issue by shinji2000** [chainpoint/chainpoint-node#33]
I think my node work well, but there are no logs about credit .
So I would like to renewal my chainpoint node with credit and NODE TNT ADDRESS.

How to do this ?

please let me know.

**Comment by sgarciafer** [comment]
There is no log about credits because Tierion is not sending hashes at the moment. That will happen tough, you need to be patient.

**Comment by sgarciafer** [comment]
Another thing you can do is to manually send a hash to your node. That will consume 1 credit and will show the total amount of credits you have.

**Comment by shinji2000** [comment]
I see I can't move to a new machine currently.

https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions

**Comment by shinji2000** [comment]
Hi sgarciafer,
Thank you.
