### ISSUE TITLE
Please refund because some people mistakenly purchased credit

### ISSUE THREAD

**Issue by liquidfunc** [chainpoint/chainpoint-node#34]
In the early days, it seems that some people thought that it was necessary to transmit 2500 TNT for credit (I also do).

From here you can check the send of TNT of 2500 ~ 3000.
https://etherscan.io/token/0x08f5a9235b08173b7569f83645d2c7fb55e8ccd8?a=0xddfff2b78463ab1ca781e853bb888fdfd06083d3

I know about [Frequently-Asked-Questions](https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions).
` no undo's in Blockchain.` Yes, right.

**Do you mean to manage TNT nodes for more than 10 years while paying server costs?**
People who make mistakes think of themselves as slaves and may hate Tierion.
such PoS(Proof of Slave).

Even if the block chain can not be changed, it can be added later.
It is a solution, if you burn credit of the applicant and refund TNT from the support team.

**Comment by sgarciafer** [comment]
it was not mentioned on the official guides how to setup a node?

**Comment by accrubit** [comment]
It was made explicitly clear in the github files what the requirements were for setting up a node and in what order to do them in. I feel for you on this matter, because it sucks, but it's not Tierions fault.

Maybe they will be nice, but what then? If they set the precedent for paying back everyone's development errors, how will that affect the operation of the business? Not good I can tell you that. 

I hope you saved the HMAC key for that node because you will have those credits a long time. Plus side is that node will probably pay you back 3 fold what you paid into it down the long stretch. Good luck.

**Comment by jnst** [comment]
With today's update credit has become completely unnecessary.

```
Nodes will receive enough credits to submit the maximum number of hashes to Core per day.
Nodes under max load will submit one hash per second to Core, and there are 86,400 seconds per day.
Users with a credit balance under 86,400 now have a credit balance of 86,400.
Credits will be used throughout the day.
At UTC midnight, nodes with a balance below 86,400 will have their credit balance restored to 86,400.
This credit model will remain active until further notice.
At this time, there is no need to convert TNT to credits.
```

My asset is completely worthless. 
Very sad 😥

**Comment by jnst** [comment]
With today's update credit has become completely unnecessary.

```
Nodes will receive enough credits to submit the maximum number of hashes to Core per day.
Nodes under max load will submit one hash per second to Core, and there are 86,400 seconds per day.
Users with a credit balance under 86,400 now have a credit balance of 86,400.
Credits will be used throughout the day.
At UTC midnight, nodes with a balance below 86,400 will have their credit balance restored to 86,400.
This credit model will remain active until further notice.
At this time, there is no need to convert TNT to credits.
```

My asset is completely worthless.
Very sad 😥

**Comment by liquidfunc** [comment]
With today's update credit has become completely unnecessary.

```
Nodes will receive enough credits to submit the maximum number of hashes to Core per day.
Nodes under max load will submit one hash per second to Core, and there are 86,400 seconds per day.
Users with a credit balance under 86,400 now have a credit balance of 86,400.
Credits will be used throughout the day.
At UTC midnight, nodes with a balance below 86,400 will have their credit balance restored to 86,400.
This credit model will remain active until further notice.
At this time, there is no need to convert TNT to credits.
```

My asset is completely worthless.
Very sad 😥

**Comment by Euroanchor** [comment]
I'm fucking done with this bullshit.

**Comment by grempe** [comment]
We have temporarily removed the need to submit TNT for credits. We will announce an update to the credit usage model in the near future. Your original TNT submission has been logged and will be accounted for in the update to the model. In the interim we have provided your account with all of the credits needed to operate at full load throughout every day. This is not a technical issue. Closing.
