### ISSUE TITLE
409 error

### ISSUE THREAD

**Issue by rjlynch** [chainpoint/chainpoint-node#36]
Starting a new node on fresh vm.
Tailing the logs returns 409
```
chainpoint-node_1  | 2017-09-19T20:17:06.788122497Z Retrieving Node calendar most recent block info
chainpoint-node_1  | 2017-09-19T20:17:06.794014349Z Node calendar height = 27999
chainpoint-node_1  | 2017-09-19T20:17:06.841532421Z An error has occurred on startup: Error: Invalid response : 409 : 409 - {"code":"InvalidArgument","message":"invalid request, toHeight must be a positive integer"}
chainpoint-node_1  | 2017-09-19T20:17:06.851913240Z error Command failed with exit code 1.
chainpointnode_chainpoint-node_1 exited with code 1
```

**Comment by SpiryMedia** [comment]
An error has occurred on startup: Error: Invalid response : 409

**Comment by sgarciafer** [comment]
same here. looks like something went wrong on the last commit of code at the core (?)

**Comment by accrubit** [comment]
Same here, only affecting new nodes installed per instructions.

**Comment by deathtech69** [comment]
Having the same problem on all my nodes, if you do a make down and a make up; This will start to happen.

**Comment by shinji2000** [comment]
Same me. 

to Height must be a positive integer"}

**Comment by grempe** [comment]
This issue should be resolved. Please upgrade to the latest version of the Node sofware as described in the FAQ page of the Wiki on this repo.
