### ISSUE TITLE
Could not read calendar block range 443: error undefined ...Retrying in 5 seconds...

### ISSUE THREAD

**Issue by adamluc** [chainpoint/chainpoint-node#38]
example:

chainpoint-node_1  | 2017-09-20T01:35:04.858271345Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:35:24.931439256Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:35:44.984824338Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:36:14.963245021Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:36:54.024720099Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:37:24.498302802Z Could not read calendar block range 442: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:37:47.038389421Z Validated and stored Core blocks 44200 to 44299
chainpoint-node_1  | 2017-09-20T01:38:04.445395246Z Could not read calendar block range 443: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:38:29.050910638Z Could not read calendar block range 443: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:38:49.171699020Z Could not read calendar block range 443: error undefined ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-20T01:39:09.224869441Z Could not read calendar block range 443: error undefined ...Retrying in 5 seconds...

**Comment by 1ce** [comment]
+1

**Comment by takeratta** [comment]
+1

**Comment by canteboi** [comment]
+1

**Comment by grempe** [comment]
This issue should be resolved. Please leave your Node running, after upgrading to the latest release of the Node software as described in the FAQ page of the Wiki.
