### ISSUE TITLE
An error has occurred on startup:

### ISSUE THREAD

**Issue by huanghao2008** [chainpoint/chainpoint-node#4]
chainpoint-node_1  | 2017-09-17T10:27:41.028220895Z An error has occurred on startup: StatusCodeError: 500 - {"code":"InternalServerError","message":"server error"}
chainpoint-node_1  | 2017-09-17T10:27:41.033894086Z error Command failed with exit code 1.

**Comment by grempe** [comment]
This is likely caused by a temporary server side issue which has now been resolved. Thanks for the report.
