### ISSUE TITLE
No matching manifest for linux/arm in the manifest list entries

### ISSUE THREAD

**Issue by saulve** [chainpoint/chainpoint-node#42]
I'm setting a node on a PC with ARM processor and ran into an issue when peforming `make up` command:
`ERROR: no matching manifest for linux/arm in the manifest list entries`. I understand that this is likely because, I'm using Armbian Linux distro which has not been added yet. Would it be possible to add settings for Armbian (even if it just copies the settings for Ubuntu 16.04)?

**Comment by grempe** [comment]
This is an unsupported configuration at this time.
