### ISSUE TITLE
Node is returning "Blockrange 468 is not ready yet" and Credit reset to "0". 

### ISSUE THREAD

**Issue by hcheemala** [chainpoint/chainpoint-node#43]
root@ubuntu-512mb-sfo2-01:~/chainpoint-node# make logs
docker-compose logs -f -t | grep chainpoint-node
Attaching to chainpointnode_chainpoint-node_1, chainpointnode_postgres_1, chainpointnode_redis_1
chainpoint-node_1  | 2017-09-20T15:55:40.806953037Z yarn start v0.24.6
chainpoint-node_1  | 2017-09-20T15:55:40.885462512Z $ node server.js
chainpoint-node_1  | 2017-09-20T15:55:42.017672936Z Redis connection established.
chainpoint-node_1  | 2017-09-20T15:55:42.027906618Z CoreHost selected from DNS : b.chainpoint.org
chainpoint-node_1  | 2017-09-20T15:55:42.128845702Z Postgres connection established.
chainpoint-node_1  | 2017-09-20T15:55:42.144862044Z Found existing Node authentication key for TNT address 0x5d60cb82fe3ecaecf09ab11f82a6c6bdd3c7fad2
chainpoint-node_1  | 2017-09-20T15:55:42.421714175Z Node registration with Core confirmed and updated.
chainpoint-node_1  | 2017-09-20T15:55:42.422083534Z ******************************************************************************
chainpoint-node_1  | 2017-09-20T15:55:42.422101614Z ******************************************************************************
chainpoint-node_1  | 2017-09-20T15:55:42.452086775Z Initial public key import completed.
chainpoint-node_1  | 2017-09-20T15:55:42.458304652Z Node syncing local calendar with Core...
chainpoint-node_1  | 2017-09-20T15:55:42.458832244Z Validating Node Calendar blocks...
chainpoint-node_1  | 2017-09-20T15:55:44.836395585Z Validated Node Calendar blocks 0 to 46899
chainpoint-node_1  | 2017-09-20T15:55:44.843399863Z Retrieving Node Calendar most recent block info
chainpoint-node_1  | 2017-09-20T15:55:44.849876329Z Node Calendar height = 46899
chainpoint-node_1  | 2017-09-20T15:55:45.099484442Z Blockrange 469 not ready yet
chainpoint-node_1  | 2017-09-20T15:55:45.101991232Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-20T15:55:46.686285783Z Core audit challenge solution calculated - a301266050b53e02e6281c19b84e16ad8b7dc6c21ca848da286789d1d41117ca
chainpoint-node_1  | 2017-09-20T16:00:45.348711289Z Blockrange 469 not ready yet
chainpoint-node_1  | 2017-09-20T16:05:45.269422641Z Blockrange 469 not ready yet

I started node yesterday and every thing looks good at that time. Initially, i have 20989 credits at 1 p.m, but at the time of 8 p.m credits decreased to 8000 ( I lost almost 12000. I have 479 total hashes). Today there are more errors due to that I did the git pull and run the make up. 
Now it is not returning to any credits.

**Comment by grempe** [comment]
Regarding the blockrange not ready see:
https://github.com/chainpoint/chainpoint-node/issues/40#issuecomment-330877092

We have temporarily halted the need to send TNT for credits. Your account will automatically be topped up with the credits you need to operate for a day, every day at Midnight UTC.

**Comment by hcheemala** [comment]
Thanks for the update about Credit.  In node, I am facing following error "Blockrange 469 not ready yet" . Please suggest how to resolve this error.

**Comment by grempe** [comment]
I just provided you with a link to my comment on the 'not ready yet' message. It is neither a bug, nor an error. It is purely informational. Please see the link I provided.
