### ISSUE TITLE
New node has 0 credit

### ISSUE THREAD

**Issue by memopo** [chainpoint/chainpoint-node#44]
I've a new node running. Testing for credit level by submitting a hash to the node yields

`Could not submit hash to Core: Invalid response : 403 : 403 - {"code":"NotAuthorized","message":"insufficient tntCredit remaining: 0"}`

Should we still need to convert TNT to credits ?

**Comment by grempe** [comment]
You'll be assigned a full set of credits at midnight UTC (in about 4 hours). We'll work on an improvement to do this for new registrations as well.

**Comment by memopo** [comment]
ok thanks!
