### ISSUE TITLE
InternalServerError / Calender Update Error , etc.

### ISSUE THREAD

**Issue by hirokhiro** [chainpoint/chainpoint-node#5]
I encountered following errors. Plz help me.

 1. "Internal Server Error" or "Error 520" at "https://a.chainpoint.org/nodes/_myaddress_"

 2. "Calender Update Error" on Ubuntu with following message;
  _Error performing calendar update : Invalid response : 500 : 500 - {"code":"InternalError","message":""}_

 3. Similar error with #2 with following message;
  _Error performing calendar update : Validation error_

I want anybody to help me how to solve above errors.
Thanks.

**Comment by adamluc** [comment]
I am getting the same error

**Comment by grempe** [comment]
This was caused by a temporary server side issue which should now be resolved. Thanks for the report.

**Comment by hirokhiro** [comment]
You're welcome. Please keep good service. I'm happy to support Tierion.

Anybody help this topic, Plz tip here. Thanks.
0xc56a948b056184391B1829d78E275fd491Cba7eE
