### ISSUE TITLE
I would like to know how this NODE_TNT_ADDRESS is obtained

### ISSUE THREAD

**Issue by DemoDu** [chainpoint/chainpoint-node#51]
I would like to know how this NODE_TNT_ADDRESS is obtained ？？？？？  
help me ！！！！！

**Comment by canteboi** [comment]
dude your node tnt address is of course your  TNT wallet address, its specified in the [example](https://github.com/chainpoint/chainpoint-node/blob/master/.env.sample)

**Comment by grempe** [comment]
It's a regular Ethereum address, that is assigned a balance of TNT ERC20 tokens. Creating an Ethereum account and buying TNT is outside of the scope of our documentation. Perhaps start with https://www.myetherwallet.com/
