### ISSUE TITLE
error Command failed with exit code 137.

### ISSUE THREAD

**Issue by Konsulat88** [chainpoint/chainpoint-node#52]
Initial public key import completed.
chainpoint-node_1  | 2017-09-22T06:59:28.737655570Z Node syncing local calendar with Core...
chainpoint-node_1  | 2017-09-22T06:59:28.738900578Z Validating Node Calendar blocks...
chainpoint-node_1  | 2017-09-22T06:59:32.663365968Z Validated Node Calendar blocks 0 to 61299
chainpoint-node_1  | 2017-09-22T06:59:32.671903603Z Retrieving Node Calendar most recent block info
chainpoint-node_1  | 2017-09-22T06:59:32.682581456Z Node Calendar height = 61299
chainpoint-node_1  | 2017-09-22T06:59:32.968609069Z Blockrange 613 not ready yet
chainpoint-node_1  | 2017-09-22T06:59:32.972915118Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-22T06:59:34.498643894Z Killed
chainpoint-node_1  | 2017-09-22T06:59:34.500561974Z error Command failed with exit code 137.
What do I do?

**Comment by Konsulat88** [comment]
root@ubuntu-512mb-sfo2-01:~/chainpoint-node# make logs
docker-compose logs -f -t | grep chainpoint-node
Attaching to chainpointnode_chainpoint-node_1, chainpointnode_postgres_1, chainp                                                                                                                                                             ointnode_redis_1
chainpoint-node_1  | 2017-09-22T07:04:37.403494431Z yarn start v0.24.6
chainpoint-node_1  | 2017-09-22T07:04:37.487899468Z $ node server.js
chainpoint-node_1  | 2017-09-22T07:04:38.760796570Z Redis connection established                                                                                                                                                             .
chainpoint-node_1  | 2017-09-22T07:04:38.768273262Z CoreHost selected from DNS :                                                                                                                                                              b.chainpoint.org
chainpoint-node_1  | 2017-09-22T07:04:38.899456100Z Postgres connection establis                                                                                                                                                             hed.
chainpoint-node_1  | 2017-09-22T07:04:38.917287610Z Found existing Node authenti                                                                                                                                                             cation key for TNT address 0x22f9ed92b2db2165da32d231cbf4a2b82d30af94
chainpoint-node_1  | 2017-09-22T07:04:39.067692838Z Node registration with Core                                                                                                                                                              confirmed and updated.
chainpoint-node_1  | 2017-09-22T07:04:39.068095822Z ****************************                                                                                                                                                             **************************************************
chainpoint-node_1  | 2017-09-22T07:04:39.068110755Z Node private authentication                                                                                                                                                              key (back me up!): 682cd90ee2cc46fa-----------------------------------------------79a85ab4852                                                                                                                                                             e15
chainpoint-node_1  | 2017-09-22T07:04:39.068116679Z ****************************                                                                                                                                                             **************************************************
chainpoint-node_1  | 2017-09-22T07:04:39.098623787Z Initial public key import co                                                                                                                                                             mpleted.
chainpoint-node_1  | 2017-09-22T07:04:39.105047881Z Node syncing local calendar                                                                                                                                                              with Core...
chainpoint-node_1  | 2017-09-22T07:04:39.105540121Z Validating Node Calendar blo                                                                                                                                                             cks...
chainpoint-node_1  | 2017-09-22T07:04:41.332766730Z Validated Node Calendar bloc                                                                                                                                                             ks 0 to 61299
chainpoint-node_1  | 2017-09-22T07:04:41.338561750Z Retrieving Node Calendar mos                                                                                                                                                             t recent block info
chainpoint-node_1  | 2017-09-22T07:04:41.346630351Z Node Calendar height = 61299
chainpoint-node_1  | 2017-09-22T07:04:42.860194043Z Validated and stored Core bl                                                                                                                                                             ocks 61300 to 61399
chainpoint-node_1  | 2017-09-22T07:04:42.958286115Z Blockrange 614 not ready yet
chainpoint-node_1  | 2017-09-22T07:04:42.961423482Z Node startup completed succe                                                                                                                                                             ssfully!
chainpoint-node_1  | 2017-09-22T07:04:51.146980009Z Killed
chainpoint-node_1  | 2017-09-22T07:04:51.151580948Z error Command failed with ex                                                                                                                                                             it code 137.
chainpointnode_chainpoint-node_1 exited with code 1
      In the beginning writes

**Comment by takecian** [comment]
#46
