### ISSUE TITLE
After git pull, get new error

### ISSUE THREAD

**Issue by hirokhiro** [chainpoint/chainpoint-node#54]
I got this error after updating.

docker-compose up -d --no-build
Pulling chainpoint-node (quay.io/chainpoint/chainpoint-node:74fe7fb1f68d7665e377e0ab9a9379825ec008b3)...
ERROR: Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Makefile:19: recipe for target 'up' failed
make: *** [up] Error 1

**Comment by grempe** [comment]
This was apparently Docker having a networking issue on your machine pulling from quay.io (temporarily?). This is not something within our control as that is completely controlled by Docker code and your network setup.
