### ISSUE TITLE
Using memory too much!!

### ISSUE THREAD

**Issue by jnst** [chainpoint/chainpoint-node#58]
The latest version uses memory **too much** during synchronization.
It does not work normaly without a swap file.

**Syncing:**
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           486M        324M        6.1M         80M        156M         47M
Swap:          1.0G        173M        850M
```

**Sync completed:**
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           486M        164M        102M         89M        220M        198M
Swap:          1.0G         88M        935M
```

In the previous version, it was able to run without a swap file.
Now I got an error and terminal stuck. (I solved it after setting the swap file.)

Is it possible to improve performance?

**Comment by grempe** [comment]
The application will use what the application needs to use. We have not changed anything that I am aware of that would affect memory usage of the application in our releases. If you find your server doesn't have enough RAM, then I suggest you upgrade your server.

**Comment by jnst** [comment]
Wow, Wiki already updated to 1GB from 512MB.

```
How much RAM does my Node server need?

We see best results with servers that have at least 1GB of RAM available.
Servers with less than 1GB of RAM will likely need at least a swap file configured, but may not perform as well.
See other answers related to RAM on this page.
```
