### ISSUE TITLE
Logs seems ok, but the audit error,

### ISSUE THREAD

**Issue by wingolden** [chainpoint/chainpoint-node#59]
chainpoint-node_1  | 2017-09-24T00:41:30.961529390Z Validated and stored Core blocks 99500 to 99599
chainpoint-node_1  | 2017-09-24T00:56:30.963435493Z Validated and stored Core blocks 99600 to 99699
chainpoint-node_1  | 2017-09-24T01:11:30.977301719Z Validated and stored Core blocks 99700 to 99799
chainpoint-node_1  | 2017-09-24T01:26:31.012971153Z Validated and stored Core blocks 99800 to 99899
chainpoint-node_1  | 2017-09-24T01:41:30.990409656Z Validated and stored Core blocks 99900 to 99999
chainpoint-node_1  | 2017-09-24T01:56:31.028382104Z Validated and stored Core blocks 100000 to 100099

my logs, but audit says.

	IP Test	Time test	Calendar test	Credit test
	FALSE	FALSE	   FALSE	           TRUE

what is the problem. I'm using AWS...

**Comment by deathtech69** [comment]
having the same problem, the tests from chainpoint all say false, minus the min credits. however i can submit a hash myself just fine.

**Comment by grempe** [comment]
Your server is likely not available publicly, and available for our Core servers to audit. Please confirm that the host is reachable from another Internet host. at `http://YOUR-IP/config`

If the site is not available publicly, the time and calendar state tests will also fail.

**Comment by deathtech69** [comment]
They are ALL indeed visible via the public i can hit each one via my ip/public with no issues at all. However, that issue is in the back burner now as i'm getting the  error 500 and the Could not read calendar block range 1070 ...Retrying in 5 seconds... on all of them now.
