### ISSUE TITLE
Unable to register Node with Core: error 522

### ISSUE THREAD

**Issue by koheihamada** [chainpoint/chainpoint-node#63]
chainpoint-node_1  | 2017-09-24T13:32:00.955972022Z Found existing Node authentication key for TNT address 0xfc7f8xxxxxxxxxxxxxxxxxxx428435f0
chainpoint-node_1  | 2017-09-24T13:32:16.420398219Z Unable to register Node with Core: error 522 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T13:32:21.431031770Z Found existing Node authentication key for TNT address 0xfc7f8xxxxxxxxxxxxxdf104c219428435f0
chainpoint-node_1  | 2017-09-24T13:32:36.908683599Z Unable to register Node with Core: error 522 ...Retrying in 5 seconds...

git pull didnt help does anyone know how to fix this?

**Comment by Guy-JP** [comment]
I am having same issue, do you think its system wide?

**Comment by n0bility6** [comment]
Me also, have the same issue, the server  was down an hour ago? any idea?

**Comment by grempe** [comment]
Duplicate. https://github.com/chainpoint/chainpoint-node/issues/70#issuecomment-332270424
