### ISSUE TITLE
Unable to register Node with Core: error 522 ...Retrying in 5 seconds...

### ISSUE THREAD

**Issue by Guy-JP** [chainpoint/chainpoint-node#64]
Hi,

My node was up and running fine, however now when I attempt to run it, it repeats the error meesage "Unable to register Node with Core: error 522 ...Retrying in 5 seconds..."
Unit it finally it says " error Command failed with exit code 1." 

How do I resolve this? Thanks.

**Comment by grempe** [comment]
Duplicate. https://github.com/chainpoint/chainpoint-node/issues/70#issuecomment-332270424
