### ISSUE TITLE
 Unable to register Node with Core: error 500 ...Retrying in 5 seconds...

### ISSUE THREAD

**Issue by n0bility6** [chainpoint/chainpoint-node#65]
Hi Guyz, new error afte the 522 any idea?

**Comment by radeone** [comment]
went to sleep everything was working fine woke up and now its having the same error

**Comment by Octron4** [comment]
i have the same Problem... note that i just set it up and its the first node for me

**Comment by deathtech69** [comment]
having the same issue on some of my nodes.

**Comment by n0bility6** [comment]
@deathtech69 it means some of your nodes are working right?

**Comment by Octron4** [comment]
i m using amazon light weight sail (512 mb ram) ....

**Comment by deathtech69** [comment]
n0bility6 i looked the chainpoint website which audits it and it said a few were fine, but looking int the make logs, yea thats not true they are all down doing the same issue now.

**Comment by n0bility6** [comment]
@deathtech69 Thanks for verification, I will wait and do nothing for the mean time.. Please comment here if the system is already working. Thanks

**Comment by radeone** [comment]
i think its a cloudflare issue

**Comment by radeone** [comment]
chainpoint-node_1  | 2017-09-24T15:51:43.924413009Z Node startup error : StatusCodeError: 403 - "<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/zepto.min.js\"></script>\n<script type=\"text/javascript\" src=\"/cdn-cgi/scripts/cf.common.js\"></script>\n\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n      <div class=\"cf-wrapper cf-header cf-error-overview\">\n        <h1 data-translate=\"block_headline\">Sorry, you have been blocked</h1>\n        <h2 class=\"cf-subheadline\"><span data-translate=\"unable_to_access\">You are unable to access</span> chainpoint.org</h2>\n      </div>\n\n      <div class=\"cf-section cf-highlight\">\n        <div class=\"cf-wrapper\">\n          <div class=\"cf-screenshot-container cf-screenshot-full\">\n            \n              <span class=\"cf-no-screenshot error\"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-section cf-wrapper\">\n        <div class=\"cf-columns two\">\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_why_headline\">Why have I been blocked?</h2>\n\n            <p data-translate=\"blocked_why_detail\">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class=\"cf-column\">\n            <h2 data-translate=\"blocked_resolve_headline\">What can I do to resolve this?</h2>\n\n            <p data-translate=\"blocked_resolve_detail\">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class=\"cf-error-footer cf-wrapper\">\n  <p>\n    <span class=\"cf-footer-item\">Cloudflare Ray ID: <strong>3a36e8238c6079bb</strong></span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"your_ip\">Your IP</span>: 35.166.234.153</span>\n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\"><span data-translate=\"performance_security_by\">Performance &amp; security by</span> <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing?utm_source=error_footer\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n    <span class=\"cf-footer-separator\">&bull;</span>\n    <span class=\"cf-footer-item\">\n      <select id=\"lang-selector\">\n        <option value=\"\">Select a Language</option>\n        <option value=\"en\">English</option>\n        <option value=\"es\">Español</option>\n      </select>\n    </span>\n    \n  </p>\n</div>\n\n\n    </div>\n  </div>\n\n  <script type=\"text/javascript\">\n  window._cf_translation = {};\n  window._cf_translation.locale = 'en';\n  window._cf_translation.blobs = {};\n</script>\n\n</body>\n</html>\n"
chainpoint-node_1  | 2017-09-24T15:51:43.933152184Z error Command failed with exit code 1.

**Comment by radeone** [comment]
i did a make down and ill wait a few hours until i put mine back up.

**Comment by radeone** [comment]
now its doing this:
chainpoint-node_1  | 2017-09-24T16:04:55.003757364Z Validated and stored Core blocks 108200 to 108299
chainpoint-node_1  | 2017-09-24T16:05:05.534136593Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:05:05.535838971Z Node startup completed successfully!
chainpoint-node_1  | 2017-09-24T16:05:21.731328123Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:05:38.944402045Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:05:54.628320887Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:06:10.564655316Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:06:26.115307562Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:06:41.841491658Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:06:57.641783040Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:07:13.380709627Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:07:28.955383953Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:07:44.526722356Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:08:04.785551268Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:08:20.695370693Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:08:36.759319389Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:21.077252436Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:23.050178941Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:36.858023971Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:38.757056931Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:52.424830441Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:10:54.488412838Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:07.866048424Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:10.827667543Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:23.397738866Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:26.263094037Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:39.146473026Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:11:54.839216094Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:01.267866623Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:10.768039361Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:17.768057549Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:26.866885699Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:34.241290902Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:43.117086983Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:50.351702820Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:12:58.648551265Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:06.082522345Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:14.349295142Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:22.649184119Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:30.171632948Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:39.772390128Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:45.279031062Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:13:55.655304922Z Could not read calendar block range 1083 ...Retrying in 5 seconds...
chainpoint-node_1  | 2017-09-24T16:14:02.428253315Z Could not read calendar block range 1083 ...Retrying in 5 seconds...

**Comment by n0bility6** [comment]
Yeah im getting the same issue.

**Comment by radeone** [comment]
do a make down and git pull theres an update to the docker.yaml

**Comment by n0bility6** [comment]
Hi Guyz, Mine worked already.

make down
git pull
make up
make logs

**Comment by Guy-JP** [comment]
Tried the above (git pull) but still getting same issue

**Comment by radeone** [comment]
whats it saying guy

**Comment by Guy-JP** [comment]
Fixed it... forgot to recreate the 1G swapfile Thanks

**Comment by n0bility6** [comment]
New update. Minimum TNT Token is 5k and reward every 30 min is now 500 TNT.

See reference: https://medium.com/tierion/tierion-network-update-september-24-6242fdb30111

**Comment by grempe** [comment]
Duplicate. https://github.com/chainpoint/chainpoint-node/issues/70#issuecomment-332270424
