### ISSUE TITLE
Authorization denied

### ISSUE THREAD

**Issue by muntasirjoarder** [chainpoint/chainpoint-node#7]
chainpoint-node_1  | 2017-09-17T13:29:26.115963424Z Error querying for proofs on Core : Invalid response : 401 : 401 - {"code":"InvalidCredentials","message":"authorization denied: ResourceRequest timed out"}

**Comment by grempe** [comment]
Thanks for the report. We are looking into a resolution for this now.

**Comment by adamluc** [comment]
I am also getting the same error: 

chainpoint-node_1  | 2017-09-17T13:55:24.823542177Z Could not submit hash to Core: Invalid response : 401 : 401 - {"code":"InvalidCredentials","message":"authorization denied: ResourceRequest timed out"}

**Comment by adamluc** [comment]
I have also gotten this message: chainpoint-node_1  | 2017-09-17T14:01:10.394271178Z Could not submit hash to Core: Invalid response : 401 : 401 - {"code":"InvalidCredentials","message":"authorization denied: ResourceRequest timed out"}

**Comment by grempe** [comment]
This was a temporary server side issue. This should be fully resolved now. Closing.
