### ISSUE TITLE
 Node registration failed with status code : 404 ..

### ISSUE THREAD

**Issue by yuuhi0320** [chainpoint/chainpoint-node#70]
The error such as follows occurs.
What should I do?
↓
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 Node registration failed with status code : 404 ...Retrying in 60 seconds...
chainpoint-node_1  | 2017-09-25T10:27:57.486979107Z Done in 185.03s.
chainpoint-node_1  | 2017-09-25T10:47:35.304941102Z yarn start v0.24.6
chainpoint-node_1  | 2017-09-25T10:47:35.463262209Z $ node server.js
chainpoint-node_1  | 2017-09-25T10:47:38.815902785Z INFO : Core host selected : a.chainpoint.org
chainpoint-node_1  | 2017-09-25T10:47:39.218269323Z INFO : No local Node authentication key for TNT address
 0x73dff8a94e64d4f16427b3ad851820b5a20a80f7. Registering.
chainpoint-node_1  | 2017-09-25T10:47:39.358760896Z ERROR : Unable to register Node with Core: error ERROR:
 Node registration failed with status code : 404 ...Retrying in 60 seconds...
chainpoint-node_1  | 2017-09-25T10:48:39.370154255Z INFO : No local Node authentication key for TNT address
 0x73dff8a94e64d4f16427b3ad851820b5a20a80f7. Registering.
chainpoint-node_1  | 2017-09-25T10:48:39.475961848Z ERROR : Unable to register Node with Core: error ERROR:
 Node registration failed with status code : 404 ...Retrying in 60 seconds...
chainpoint-node_1  | 2017-09-25T10:49:39.482019203Z INFO : No local Node authentication key for TNT address
 0x73dff8a94e64d4f16427b3ad851820b5a20a80f7. Registering.
chainpoint-node_1  | 2017-09-25T10:49:39.571716018Z ERROR : Unable to register Node with Core: error ERROR:
 Node registration failed with status code : 404 ...Retrying in 60 seconds...

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by serdarozturk** [comment]
@yuuhi0320  i have same problem.

node registration seems to be closed on source code.

they disabled register route. 
`
// register a new node
// server.post({ path: '/nodes', version: '1.0.0' }, nodes.postNodeV1Async)
`

**Comment by mlep1** [comment]
Exact same error here

**Comment by seasapart** [comment]
same exact error here as well, so does that mean that all the nodes are currently down or just new nodes?

**Comment by serdarozturk** [comment]
@seasapart new node registration disabled. old nodes running for dev team testing.

**Comment by grempe** [comment]
We have temporarily disabled new Node registration. Please follow us in Telegram, or an Twitter for new information when we re-open registration.
