### ISSUE TITLE
Cannot move node to another server

### ISSUE THREAD

**Issue by sgarciafer** [chainpoint/chainpoint-node#71]
Due to new memory requirements some servers are not working anymore. I need to move them to another infrastructure but:

1. The backup system of a node is not enable.
2. We cannot create new nodes.

**Comment by grempe** [comment]
Your auth keys are now portable between systems. If you have a backup of your auth key, from a previous registration, you can use it along with your Ethereum address on another host.

See:
https://github.com/chainpoint/chainpoint-node#node-authentication-key-backuprestore
