### ISSUE TITLE
IP's unusable after being used once by a deleted node

### ISSUE THREAD

**Issue by sgarciafer** [chainpoint/chainpoint-node#73]
I had a node that I made for testing purposes that was deleted. Now I want to use the same server to host a new node, but is not possible because the IP of the server has been already linked to that prior node.

`chainpoint-node    | 2017-10-05T22:39:43.143785210Z ERROR : Registration update error : http://145.XXX.XX.XX : ConflictError : public URI is already in use`

Could we have the possibility to re-use the same server IP for other node, while avoiding that two nodes pass audits at the same time from the same IP?

**Comment by grempe** [comment]
This is working as designed. This limitation is in place to help prevent abuse. At least for now you'll need to use another IP address for bringing your Node back up.

**Comment by sgarciafer** [comment]
you would agree with me that paying two times for a hosting is pretty
inconvenient and waste of resources...
There are other options to assure there is only one node per IP while
allowing more flexibility. I hope you will make your mind about this point.
