### ISSUE TITLE
Could not submit hash to Core: ERROR : Invalid response : 429

### ISSUE THREAD

**Issue by mikevdl** [chainpoint/chainpoint-node#74]
When submitting a hash it gives the following error:

chainpoint-node    | 2017-10-07T10:59:53.086988487Z INFO : Syncing local Calendar with Core...
chainpoint-node    | 2017-10-07T10:59:53.088852992Z INFO : Validating local Calendar blocks...
chainpoint-node    | 2017-10-07T11:00:02.342091037Z INFO : Validated blocks 0 to 99999
chainpoint-node    | 2017-10-07T11:00:13.991770376Z INFO : Validated blocks 100000 to 199999
chainpoint-node    | 2017-10-07T11:00:14.706801042Z INFO : Validated blocks 200000 to 206399
chainpoint-node    | 2017-10-07T11:00:14.830633052Z INFO : Startup completed!
chainpoint-node    | 2017-10-07T11:01:22.413679572Z INFO : Building aggregation tree with 1 hash(es) for this interval
chainpoint-node    | 2017-10-07T11:01:22.671004524Z ERROR : Could not submit hash to Core: ERROR : Invalid response : 429

**Comment by grempe** [comment]
Thanks for the report. This means your Node has been rate limited for submitting hashes too frequently. This should not happen in normal operation. Please indicate which version of the Node software you are running (or the git commit sha1) as well.

**Comment by grempe** [comment]
I've made a change to the rate limiting which should resolve this issue. If not, please re-open with more details.

**Comment by mikevdl** [comment]
Hi Glen,

I run two nodes with version 1.1.10. Both had the same problem.

The issue is solved by your change.

Thanks for your quick respond!

Kind regards,

Mike
