### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by kensho2000** [chainpoint/chainpoint-node#78]
After starting node and starup, node show below error and closed loop
"start up -> error -> start up -> error"....

chainpoint-node    | 2017-11-30T02:44:49.240531004Z INFO : App : Startup completed!
chainpoint-node    | 2017-11-30T02:45:18.939934528Z buffer.js:38
chainpoint-node    | 2017-11-30T02:45:18.989931935Z     super(arg1, arg2, arg3);
chainpoint-node    | 2017-11-30T02:45:18.989963747Z     ^
chainpoint-node    | 2017-11-30T02:45:18.989968025Z 
chainpoint-node    | 2017-11-30T02:45:18.989971197Z RangeError: Array buffer allocation failed
chainpoint-node    | 2017-11-30T02:45:18.989974568Z     at new ArrayBuffer (<anonymous>)
chainpoint-node    | 2017-11-30T02:45:18.989978186Z     at typedArrayConstructByLength (<anonymous>)
chainpoint-node    | 2017-11-30T02:45:18.989981575Z     at new Uint8Array (native)
chainpoint-node    | 2017-11-30T02:45:18.989984512Z     at new FastBuffer (buffer.js:38:5)
chainpoint-node    | 2017-11-30T02:45:18.989987607Z     at Function.Buffer.alloc (buffer.js:243:10)
chainpoint-node    | 2017-11-30T02:45:18.989998083Z     at new Buffer (buffer.js:156:19)
chainpoint-node    | 2017-11-30T02:45:18.990001076Z     at module.exports.Reader.addChunk (/home/node/app/node_modules/packet-reader/index.js:35:21)
chainpoint-node    | 2017-11-30T02:45:18.990003907Z     at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:126:18)
chainpoint-node    | 2017-11-30T02:45:18.990006958Z     at emitOne (events.js:116:13)
chainpoint-node    | 2017-11-30T02:45:18.990009532Z     at Socket.emit (events.js:211:7)
chainpoint-node    | 2017-11-30T02:45:18.990012268Z     at addChunk (_stream_readable.js:263:12)
chainpoint-node    | 2017-11-30T02:45:18.990014872Z     at readableAddChunk (_stream_readable.js:250:11)
chainpoint-node    | 2017-11-30T02:45:18.990017611Z     at Socket.Readable.push (_stream_readable.js:208:10)
chainpoint-node    | 2017-11-30T02:45:18.990020359Z     at TCP.onread (net.js:594:20)
chainpoint-node    | 2017-11-30T02:45:18.990028312Z error Command failed with exit code 1.
chainpoint-node    | 2017-11-30T02:45:20.044064166Z yarn run v1.2.1
chainpoint-node    | 2017-11-30T02:45:21.383465616Z INFO : App : Starting : Version 1.3.1
chainpoint-node    | 2017-11-30T02:45:21.584035686Z INFO : App : Core Host : a.chainpoint.org

......loop.

**Comment by grempe** [comment]
Thanks for the report. Please describe the hardware (RAM, # CPU, OS + version) you are running this Node on, and if possible a screenshot or copy paste of the output reported by `top` while the Node is cycling.

When we have seen this error before it has been the result of too little RAM.

Has this Node been operating normally before? Or is it a new Node?

**Comment by grempe** [comment]
https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions#i-am-seeing-range-error-array-buffer-allocation-failed-messages-in-the-logs-what-gives

**Comment by kensho2000** [comment]
The timing of error is depend on,
after several auto restart, it work normal few new process, and fail again.
I attach my log again.
![2017-12-01 12 55 50](https://user-images.githubusercontent.com/32006692/33469957-53cd348e-d698-11e7-87b1-bfe27009b3f7.png)

* Hardware: 
   CPU:1 vCore, RAM:1024 MB, Storage: 25 GB SSD 
   OS: Ubuntu 16.04 x64 
Node worked normally before, 
but, I think it was happened from 1.2 upgrade. not from 1.3

**Comment by kensho2000** [comment]
top
![2017-12-01 13 08 47](https://user-images.githubusercontent.com/32006692/33470050-ee0003e2-d698-11e7-8953-2922db5fbeef.png)

**Comment by grempe** [comment]
Thanks for the additional information. Can you confirm whether this issue persists after a reboot of the server?

**Comment by kensho2000** [comment]
I reboot server and up garade 1.3.2. But, still same...
![2017-12-02 23 21 37](https://user-images.githubusercontent.com/32006692/33518071-a22ead18-d7c1-11e7-8b82-0c6b357eb5f7.png)

**Comment by kensho2000** [comment]
I have some warning I never seen before at make up & make down now.
Is this warning related to loop problem?
I show you the log from my make up to make down.
![2017-12-03 0 55 12](https://user-images.githubusercontent.com/32006692/33518334-d5c295e6-d7c5-11e7-9be3-75d6d1c1c056.png)

**Comment by grempe** [comment]
The warning about `orphan containers` is an expected part of working with docker-compose with two `docker-compose.yaml` files. It can be ignored. I will add a FAQ entry for it.

The Array buffer allocation issue is due to insufficient RAM (Google will return many results for Array buffer allocation failures that are also RAM related). I suggest you try a reboot and consider either a larger instance or adding a swap file. https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions#i-am-seeing-range-error-array-buffer-allocation-failed-messages-in-the-logs-what-gives

**Comment by grempe** [comment]
FYI, FAQ entry added for the orphan container message.

https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions#i-am-seeing-warning--orphan-container-messages-in-the-logs

**Comment by kensho2000** [comment]
thank you for your help. I will try to add a swap file.
