### ISSUE TITLE
Cannot complete the registration(exit with code 0)

### ISSUE THREAD

**Issue by bizhonggeng** [chainpoint/chainpoint-node#79]
When I tried to run my node by click into "make up", I found it kept retrying in the logs as following, then exit with code 0. What was wrong about it? I could not find any information in FAQ.

Attaching to chainpoint-node, postgres-node, redis-node
chainpoint-node    | 2017-12-02T10:53:30.154751748Z yarn run v1.2.1
chainpoint-node    | 2017-12-02T10:53:31.290958009Z INFO : App : Starting : Version 1.3.2
chainpoint-node    | 2017-12-02T10:53:31.547495786Z INFO : App : Core Host : a.chainpoint.org
chainpoint-node    | 2017-12-02T10:53:31.848814842Z ERROR : Registration : Core : 1/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:53:32.782791110Z INFO : Firewall : Added 844 external IPs to block list
chainpoint-node    | 2017-12-02T10:53:47.047051239Z ERROR : Registration : Core : 2/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:54:02.228633711Z ERROR : Registration : Core : 3/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:54:17.401542933Z ERROR : Registration : Core : 4/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:54:32.587622564Z ERROR : Registration : Core : 5/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:54:47.760491701Z ERROR : Registration : Core : 6/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:55:02.930752219Z ERROR : Registration : Core : 7/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:55:18.128268616Z ERROR : Registration : Core : 8/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:55:33.299947725Z ERROR : Registration : Core : 9/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:55:48.474467908Z ERROR : Registration : Core : 10/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:56:03.665258584Z ERROR : Registration : Core : 11/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:56:18.834609037Z ERROR : Registration : Core : 12/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:56:34.012328160Z ERROR : Registration : Core : 13/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:56:49.186795142Z ERROR : Registration : Core : 14/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:57:04.361593384Z ERROR : Registration : Core : 15/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:57:19.534299789Z ERROR : Registration : Core : 16/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:57:34.711285319Z ERROR : Registration : Core : 17/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:57:49.885886631Z ERROR : Registration : Core : 18/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:58:05.067784646Z ERROR : Registration : Core : 19/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:58:20.243326884Z ERROR : Registration : Core : 20/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:58:35.427793909Z ERROR : Registration : Core : 21/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:58:50.616065322Z ERROR : Registration : Core : 22/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:59:05.802092329Z ERROR : Registration : Core : 23/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:59:20.984493608Z ERROR : Registration : Core : 24/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:59:36.163965846Z ERROR : Registration : Core : 25/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T10:59:51.335224730Z ERROR : Registration : Core : 26/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:00:06.534778259Z ERROR : Registration : Core : 27/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:00:21.711369764Z ERROR : Registration : Core : 28/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:00:36.889804593Z ERROR : Registration : Core : 29/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:00:52.066745485Z ERROR : Registration : Core : 30/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:01:07.241192475Z ERROR : Registration : Core : 31/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:01:22.417012838Z ERROR : Registration : Core : 32/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:01:37.592422950Z ERROR : Registration : Core : 33/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:01:52.764537540Z ERROR : Registration : Core : 34/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:02:07.936822682Z ERROR : Registration : Core : 35/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:02:23.115948291Z ERROR : Registration : Core : 36/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:02:38.285845368Z ERROR : Registration : Core : 37/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:02:53.457367170Z ERROR : Registration : Core : 38/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:03:08.623962403Z ERROR : Registration : Core : 39/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:03:23.814964946Z ERROR : Registration : Core : 40/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:03:38.991650533Z ERROR : Registration : Core : 41/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:03:54.188516144Z ERROR : Registration : Core : 42/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:04:09.375688291Z ERROR : Registration : Core : 43/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:04:24.589587616Z ERROR : Registration : Core : 44/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:04:39.773811089Z ERROR : Registration : Core : 45/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:04:54.958863972Z ERROR : Registration : Core : 46/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:05:10.145937394Z ERROR : Registration : Core : 47/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:05:25.334902137Z ERROR : Registration : Core : 48/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:05:40.508914093Z ERROR : Registration : Core : 49/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:05:55.697796842Z ERROR : Registration : Core : 50/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:06:10.896571953Z ERROR : Registration : Core : 51/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:06:26.083397948Z ERROR : Registration : Core : 52/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:06:41.253771890Z ERROR : Registration : Core : 53/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:06:56.460695279Z ERROR : Registration : Core : 54/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:07:11.629264068Z ERROR : Registration : Core : 55/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:07:26.802986951Z ERROR : Registration : Core : 56/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:07:41.984705240Z ERROR : Registration : Core : 57/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:07:57.160343893Z ERROR : Registration : Core : 58/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:08:12.331292996Z ERROR : Registration : Core : 59/60 : 403 : Retrying...
chainpoint-node    | 2017-12-02T11:08:12.339809912Z Done in 882.19s.

**Comment by grempe** [comment]
This is not a bug. This is the Node attempting to register itself. When it gives up after 60 tries the Node exits. Registration for new Nodes is currently closed. When we periodically allow new Nodes to register that is announced in both our Telegram channel and on Medium.  Please try again during such an announced event.

https://medium.com/tierion

**Comment by bizhonggeng** [comment]
Thank you for your reply!
