### ISSUE TITLE
Question : Credit decreasing

### ISSUE THREAD

**Issue by hirokhiro** [chainpoint/chainpoint-node#8]
Hello, I have one question.

My credit is decreasing rapidly during these 2-3 hours.
Finally, my "minimum_credit_test" fall down to "false".
If you have any information source, that would help me.

Although some sever error in TNT network is happening, my node is on right setting.

**Comment by kewonghk** [comment]
I have the same issue.
And I tried restart the service and it turns out I got this error
"TNT address {MyEtherAddress} cannot be registered, it is already registered and in use with an existing HMAC key"

This is weird.

**Comment by hirokhiro** [comment]
Hello, additional comment.

Maybe, we need some information about Credit comsumption.
Approximate comsumption rate by date, week, and month etc.
We need to keep credit balance appropriately for server maintenance.

Some people doesn't know that fact, and that information would be good in future of Tierion Network.

**Comment by mesnia** [comment]
I have the same issue. Its like 1 credit decreasing per second.

**Comment by Richardxlin** [comment]
Is there an economic penalty for a malicious actor who spams the node with useless hashes?

**Comment by hydrarulz** [comment]
> Is there an economic penalty for a malicious actor who spams the node with useless hashes?

As far as I know there is none. Because anybody can download and use the CLI client, send hashes to the nodes without paying anything in order to do this.

**Comment by grempe** [comment]
This is not a software bug. Please see the pinned message in the Telegram group and the README for this repository. The need to submit TNT for credits has been temporarily suspended. Your account will automatically be topped up with credits every day while we work on a more permanent resolution.
