### ISSUE TITLE
sudo: unable to stat /etc/sudoers: Permission denied

### ISSUE THREAD

**Issue by kensho2000** [chainpoint/chainpoint-node#80]
I tried making swap file follow this add.
https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions#i-am-seeing-range-error-array-buffer-allocation-failed-messages-in-the-logs-what-gives

but, at first step, it show this error.
I can not continue more.
---------# sudo swapon --show
sudo: unable to stat /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

How can I fix it?
I need to delete all data on server and re-install all from beginning?
Can I keep my node registration at that time??

**Comment by grempe** [comment]
Sorry, this is outside the scope of your project. I suggest checking the documentation for the version of Linux you are running.
