### ISSUE TITLE
Not enough TNT??

### ISSUE THREAD

**Issue by deathtech69** [chainpoint/chainpoint-node#82]
I'm getting this message on two of my nodes even though i have over 5K TNT on each wallet. Whats going on?

 Registration : Key : XXXXXXXXXXXXXXXXXXXXXX
chainpoint-node    | 2017-12-30T23:09:31.938432736Z ERROR : Registration : Core : 50/60 : 403 : TNT address 0x130bef17bba8876da25c7ec784d21f824faac9ac does not have the minimum balance of 5000 TNT for Node operation : Retrying...

EDIT
---Seems to be working now. guess some changes were being tested.

**Comment by 1ce** [comment]
me too!!

**Comment by adamevers** [comment]
This was a minor error that has now been fixed. Please make down then make up.
