### ISSUE TITLE
Unable to connect via port 80

### ISSUE THREAD

**Issue by 001dingo** [chainpoint/chainpoint-node#84]
Port 80 is open. To make sure I started apache and connected to port 80 publicly from another host.

Here are the steps:

1. Create fresh Ubuntu 16.04 LTS server with inbound 80 open to any ip
2. Run install command from ReadMe
3. Make up
4. Edit .env file with token address and IP
5. Make upgrade
6. Unable to access public ip http://[ip]/config (connection refused, port closed).

Here are my logs after make up:

Local NTPD is not running. Starting chainpoint-ntpd...
Creating network "chainpointnode_default" with the default driver
Creating chainpoint-ntpd ... 
Creating chainpoint-ntpd ... done
Creating network "chainpointnode_chainpoint-node" with driver "bridge"
WARNING: Found orphan containers (chainpoint-ntpd) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating redis-node ... 
Creating postgres-node ... 
Creating redis-node
Creating redis-node ... done
Creating chainpoint-node ... 
Creating chainpoint-node ... done

XX~/chainpoint-node$ make logs-all
Attaching to chainpoint-node, postgres-node, redis-node
chainpoint-node    | 2018-01-10T11:07:50.725464664Z yarn run v1.2.1
chainpoint-node    | 2018-01-10T11:07:50.803178225Z $ node server.js
chainpoint-node    | 2018-01-10T11:07:51.646215289Z INFO : App : Starting : Version 1.3.4
chainpoint-node    | 2018-01-10T11:07:51.836484779Z INFO : App : Core Host : c.chainpoint.org
chainpoint-node    | 2018-01-10T11:07:52.070241732Z ERROR : Registration : Core : 1/60 : 403 : Retrying...
chainpoint-node    | 2018-01-10T11:07:52.707149181Z INFO : Firewall : Added 951 external IPs to block list
postgres-node      | 2018-01-10T11:07:50.080206112Z LOG:  database system was shut down at 2018-01-10 11:07:45 UTC
postgres-node      | 2018-01-10T11:07:50.083204381Z LOG:  MultiXact member wraparound protections are now enabled
postgres-node      | 2018-01-10T11:07:50.083762797Z LOG:  database system is ready to accept connections
postgres-node      | 2018-01-10T11:07:50.089725313Z LOG:  autovacuum launcher started
redis-node         | 2018-01-10T11:07:50.021659183Z 1:C 10 Jan 11:07:50.020 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-node         | 2018-01-10T11:07:50.021702175Z 1:C 10 Jan 11:07:50.020 # Redis version=4.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
redis-node         | 2018-01-10T11:07:50.021706377Z 1:C 10 Jan 11:07:50.020 # Configuration loaded
redis-node         | 2018-01-10T11:07:50.034734976Z 1:M 10 Jan 11:07:50.033 * Running mode=standalone, port=6379.
redis-node         | 2018-01-10T11:07:50.034759263Z 1:M 10 Jan 11:07:50.033 # Server initialized
redis-node         | 2018-01-10T11:07:50.034762583Z 1:M 10 Jan 11:07:50.033 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-node         | 2018-01-10T11:07:50.034767905Z 1:M 10 Jan 11:07:50.033 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis-node         | 2018-01-10T11:07:50.034771684Z 1:M 10 Jan 11:07:50.033 * DB loaded from append only file: 0.000 seconds
redis-node         | 2018-01-10T11:07:50.034774429Z 1:M 10 Jan 11:07:50.033 * Ready to accept connections

**Comment by grempe** [comment]
I see that one of the last entries from the `chainpoint-node` service is:

```
chainpoint-node | 2018-01-10T11:07:52.070241732Z ERROR : Registration : Core : 1/60 : 403 : Retrying...
```

This indicates that you have not registered the ETH address, and you do not have a valid auth key that results from successful registration.

Also, the logs do not indicate a successful startup message from `chainpoint-node`.

Registration is currently closed for new nodes. We have been periodically allowing new nodes to register and we announce those opportunities publicly in social media.

https://medium.com/tierion

A node will not operate, and will exit after retrying registration, if it has not been registered.

Thanks for the more detailed report. I will close this issue, if you have additional information to indicate it should remain open please post that here.

**Comment by 001dingo** [comment]
Thanks @grempe. You're correct that this node is not registered. My worry is that the node will not be reachable by chainpoint services when registration is opened since port 80 is closed. Is this a valid concern?

**Comment by grempe** [comment]
Port 80 is not 'closed'. The API server has not completed initialization yet since you are not registered and have not yet synced the calendar.

I think you will find that once you complete registration the server will operate just fine. You'll be able to test it by visiting `http://YOUR_IP/config`

Cheers.
