### ISSUE TITLE
error Command failed with exit code 134.

### ISSUE THREAD

**Issue by jarobari** [chainpoint/chainpoint-node#86]
Hi,
node runs for some time but then it fails with the following error.
After server restarts it runs again but repeatedly fails.
Server is
1x CPU
1024 MB RAM
25GB storage

Could you please advise what can be a problem and how to fix it?
Thanks,
Jaro

chainpoint-node    | 2018-01-25T13:04:55.529435597Z INFO : Registration : Public URI : http://209.250.247.155
chainpoint-node    | 2018-01-25T13:04:55.738418285Z INFO : App : Starting : Version 1.3.5
chainpoint-node    | 2018-01-25T13:04:55.905152033Z INFO : Firewall : Added 953 external IPs to block list
chainpoint-node    | 2018-01-25T13:04:55.967990524Z INFO : Calendar : Local height is 1025299
chainpoint-node    | 2018-01-25T13:04:55.968494485Z INFO : Calendar : Starting Sync...
chainpoint-node    | 2018-01-25T13:04:55.969579216Z INFO : Calendar : Validating blocks...
chainpoint-node    | 2018-01-25T13:05:00.700695502Z INFO : Calendar : Validated 0 to 99999
chainpoint-node    | 2018-01-25T13:05:04.324186087Z INFO : Calendar : Validated 100000 to 199999
chainpoint-node    | 2018-01-25T13:05:08.283000093Z INFO : Calendar : Validated 200000 to 299999
chainpoint-node    | 2018-01-25T13:05:11.595323731Z INFO : Calendar : Validated 300000 to 399999
chainpoint-node    | 2018-01-25T13:05:15.653655883Z INFO : Calendar : Validated 400000 to 499999
chainpoint-node    | 2018-01-25T13:05:18.973436423Z INFO : Calendar : Validated 500000 to 599999
chainpoint-node    | 2018-01-25T13:05:22.072333228Z INFO : Calendar : Validated 600000 to 699999
chainpoint-node    | 2018-01-25T13:05:25.925127410Z INFO : Calendar : Validated 700000 to 799999
chainpoint-node    | 2018-01-25T13:05:29.316777554Z INFO : Calendar : Validated 800000 to 899999
chainpoint-node    | 2018-01-25T13:05:33.153098677Z INFO : Calendar : Validated 900000 to 999999
chainpoint-node    | 2018-01-25T13:05:34.223915543Z INFO : Calendar : Validated 1000000 to 1025299
chainpoint-node    | 2018-01-25T13:05:34.238388232Z INFO : App : Startup : completed!
chainpoint-node    | 2018-01-25T13:05:34.248307800Z INFO : App : Next auto-restart scheduled for 2018-01-26T06:06:47+00:00
chainpoint-node    | 2018-01-25T13:45:35.388511702Z INFO : Calendar : Validated 1025300 to 1025399 (New)
chainpoint-node    | 2018-01-25T14:07:35.177734599Z terminate called after throwing an instance of 'std::bad_alloc'
chainpoint-node    | 2018-01-25T14:07:35.311599855Z   what():  std::bad_alloc
chainpoint-node    | 2018-01-25T14:08:36.839963286Z Aborted (core dumped)
chainpoint-node    | 2018-01-25T14:08:36.948840504Z error Command failed with exit code 134.

**Comment by grempe** [comment]
This is almost certainly memory related. Your node, being at the absolute minimum size, likely needs swapfile added to prevent memory errors. This is a system issue, and not a code problem so I'll close. You can learn about memory issues and swap setup here:

https://github.com/chainpoint/chainpoint-node/wiki/Frequently-Asked-Questions#i-am-seeing-range-error-array-buffer-allocation-failed-messages-in-the-logs-what-gives
