### ISSUE TITLE
Time audit fails sometimes on a node with ntpd enabled

### ISSUE THREAD

**Issue by sadgb** [chainpoint/chainpoint-node#90]
Hi there. 
```
I got the node and because it is ubuntu node it has timedatectl
      Local time: Thu 2018-05-10 17:31:26 UTC
  Universal time: Thu 2018-05-10 17:31:26 UTC
        RTC time: Thu 2018-05-10 17:31:26
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
RTC in local TZ: no
```

But sometimes (not always) i receive time audit failures. Like this one

```
{"audit_at"=>1525970757979,
       "time_pass"=>false,
       "public_uri"=>"http://138.68.171.67",
       "audit_passed"=>false,
       "node_version"=>nil,
       "node_ms_delta"=>nil,
       "cal_state_pass"=>false,
       "public_ip_pass"=>false,
       "min_credits_pass"=>true,
       "tnt_balance_pass"=>true,
       "node_version_pass"=>false,
       "tnt_balance_grains"=>500000000000}

```
How could i fix that ?

PS please tell me if i should open new issues on another repository, i will transfer this

**Comment by grempe** [comment]
The reason that NTP, cal, and node version checks fail is due to the fact that they are subordinate to the public IP test. If we can't reach your Node via it's advertised URI, and access it's `/config` endpoint, none of those checks can pass.

**Comment by sadgb** [comment]
Well then i have another question
How can i find why didn't my node respond as she should? 
Is there any special information i can find in make logs ?
Because i am 100% sure that node wasn't rebooted for a long time
