### ISSUE TITLE
make upgrade doesn't start up again properly

### ISSUE THREAD

**Issue by arisAlexis** [chainpoint/chainpoint-node#95]
latest make upgrade run as root to 1.6.0 & make logs shows this:

> chainpoint-node    | 2018-08-29T17:49:47.266237737Z ERROR : App : Startup : Error: BackupAuthKeys : Unable to complete Auth key backup(s) : EACCES: permission denied, open '/home/node/app/keys/backups/xxxxxx.key

with make up it starts again properly

**Comment by grempe** [comment]
Thanks for the report. We published a workaround for this upgrade issue in the community channels which is to run `make upgrade` twice in a row. This will fix this issue.
